[Makerdiary nRF52840 M.2 Devkit] Add SDA & SDL, RX & TX to pins.c
adafruit/circuitpython pull request #3438
Opened 2020-09-18 00:47 UTC by nitz

Despite the [silk on the dock board](https://wiki.makerdiary.com/nrf52840-m2-devkit/resources/nrf52840_m2_devkit_hw_diagram_v1_0.pdf), the SDA/SCL pins weren't defined. Though, they were already defined in `mpconfigboard.h`.

Same for RX/TX. It looks like it declared `TXD` and `RXD`, so I didn't want to remove those, but I think it makes sense to have the "standard" pin names, but I moved ithem to illustrate they were all referencing the same pins.

I mimicked the whitespace I saw in the metro_nrf52840_express port.

2020-09-18 01:19 UTC, dhalbert requested changes
The build checks for trailing whitespace. There is trailing whitespace on lines 64, 68, 89, and 94 (at least).

It would be OK to remove the TXD and RXD names in favor of TX and RX, especially if this is a recently added board.

2020-09-18 01:24 UTC, nitz commented
Doh, that's what I get for trying to just do a quick edit from the github website. I pulled the branch locally and was looking at every line, losing my mind... because an addon cleaned up the whitespace for me. 🙃

Re the TXD/RXD: I feel similarly. I wasn't the one who added this board, and I didn't want to break anyone's things, but I did take a look at the official examples, and none of them are using those pin names, so I'll remove them!

2020-09-18 01:31 UTC, dhalbert commented
Could you also change the TXD and RXD in the other makerdiary boards to TX and RX? Or does the silkscreen say "TXD" and "RXD", in which case I'm not sure what to do. These are the only boards that use that "D" suffix,

2020-09-18 01:37 UTC, dhalbert commented
OK, I looked at the silks, and the Arduino-shaped M.2 devkit uses TX and RX on the board, so that change makes sense. The other boards seem to use TXD and RXD fairly consistently, so we can leave them alone. So the changes you made so far are fine.

There seem to be other labels on some boards that are not included, but we don't have to fix those here.

2020-09-18 01:38 UTC, nitz commented
So, on the Pitaya Go (`pitaya_go`), they list them as TXD/RXD [in their pinout](https://github.com/makerdiary/pitaya-go/blob/master/docs/assets/images/pitaya-go_pinout.png), but just the PXX on the silk. the MDK, they list [TXD/RXD](https://github.com/makerdiary/nrf52840-mdk/blob/master/docs/images/nrf52840-mdk-pinout.jpg) in the pinout, as well as on the silk. Same goes for the M60 keyboard.. The MDK Dongle [Seems to skip them entirely](https://github.com/makerdiary/nrf52840-mdk-usb-dongle/blob/master/docs/assets/images/nrf52840-mdk-usb-dongle-pinout.png).

2020-09-18 01:39 UTC, nitz commented
And I should check for comments before replying!

I'll make a list of pins that seem to be missing tomorrow and will make a sweep and see if I can get them all.

2020-09-18 01:41 UTC, dhalbert commented
Thanks for looking. We generally try to use the silk markings as "ground truth", and then add aliases as appropriate for convenience.

2020-09-18 18:31 UTC, nitz commented
Okay it looks like most of the other boards matched their silk. I actually found a typo in the Pitaya Go silk, so I made them an issue for that.

So on [the user button](https://github.com/adafruit/circuitpython/pull/3438/commits/5249a228a011c737401a32ff76316bef161cc086#diff-80913a65c26c088072df9451d8d98084R106-R107) for the M.2 Devkit, the silk says "USR->D2", because it's tied to D2 as well as that button. The pin name in CP was named "USR_BTN", which makes sense, but doesn't match the "USR" on the board. Opinions there?

The changes I made to the MDK USB Dongle was to comment in the alt names for the NFC pins. They were already commented in in the Pitaya Go, and were just out there because of CP's lack of support for NFC... but that's something I'm also tackling now in #3379, so it makes sense to at least have the Pitaya Go/MDK USB Dongle at least have parity in that sense.

2020-09-18 18:52 UTC, dhalbert commented
>The pin name in CP was named "USR_BTN", which makes sense, but doesn't match the "USR" on the board. Opinions there?

We usually call buttons `BUTTON_A`, `BUTTON_UP`, and the like, so `BUTTON_USR` is would be consistent with other boards.

We are having trouble with the automated builds on GitHub getting swamped and stalled for some reason, so I will be canceling the runs for your pushes for a while to let other PR's finish, and then when this is ready to test and merge I will re-run manually.

2020-09-18 21:04 UTC, nitz commented
No worries about the cancels, makes perfect sense!

Okay, I did BUTTON_USR where it made sense (either having USR on the board, or if the button was unlabeled,) so that way it will have consistency among that family. 

Any others to take a look at?

2020-09-18 23:18 UTC, dhalbert commented on ports/nrf/boards/pitaya_go/pins.c
> +  { MP_ROM_QSTR(MP_QSTR_BUTTON_USER), MP_ROM_PTR(&pin_P1_00) },
Only one thing: this is `BUTTON_USER`, and the others are `BUTTON_USR`. Did you mean `USR`? I looked at the silk and I don't see a label, but maybe I missed it.

2020-09-19 01:50 UTC, dhalbert commented on ports/nrf/boards/pitaya_go/pins.c
> +  { MP_ROM_QSTR(MP_QSTR_BUTTON_USER), MP_ROM_PTR(&pin_P1_00) },
Never mind. I see it says "USER" on the silk in the middle of the board. I missed that first time around.

2020-09-19 01:51 UTC, dhalbert approved these changes
Thank you for the original work, and your patience and diligence. :+1:

2020-09-19 01:51 UTC, merged