add LOLIN D32 S2 Board
adafruit/circuitpython pull request #3459
Opened 2020-09-23 07:43 UTC by wemos

add LOLIN D32 S2 Board

2020-09-23 14:42 UTC, ladyada commented
we cannot accept adding a port that re-use a USB VID/PID

please purchase a USB VID and assign one to your product

2020-09-23 14:54 UTC, ladyada requested changes

2020-09-23 14:54 UTC, ladyada commented on ports/esp32s2/boards/lolin_d32_s2/mpconfigboard.mk
> +USB_PID = 0x80AA
change VID and PID to your own

2020-09-23 15:36 UTC, tannewt commented
Here is info on getting a Vendor ID: https://www.usb.org/getting-vendor-id

2020-09-29 22:42 UTC, tannewt commented
@wemos Are you planning on updating this with a valid USB PID?

2020-10-08 00:29 UTC, closed without merging