Fix lost board.SPI and board.I2C
adafruit/circuitpython pull request #3603
Opened 2020-10-24 23:15 UTC by cwalther

The **first commit** brings `board.I2C` into the same state as `board.SPI` by fixing something that was clearly wrong, but by itself caused no severe problems. It thereby _introduces_ the problem described in #3581 for `board.SPI` also for `board.I2C`. See commit message for details.

The **second commit** fixes #3581 for both SPI and I2C.

I found no reason in the code or in the Git history for `reset_port()` to come before `reset_board_busses()` in `cleanup_after_vm()`, so I reversed them.

For symmetry, since setting `spi_singleton` to non-NULL occurs together with `common_hal_busio_spi_construct()`, setting it to NULL should also occur together with `common_hal_busio_spi_deinit()` (and likewise for I2C). This makes the pins resettable and allows the swapped `reset_port()` to do its job. (The symmetry is not complete because `common_hal_busio_spi_deinit()` can also occur without setting `spi_singleton` to NULL, i.e. `spi_singleton` can end up pointing at a non-NULL deinited object. This is dealt with in the third commit, see below.)

Another desirable symmetry would be that since `common_hal_displayio_fourwire_construct()` calls `common_hal_busio_spi_never_reset()`, `common_hal_displayio_fourwire_deinit()` should also call `common_hal_busio_spi_reset()` (which doesn’t exist, but would do the reverse of `…_never_reset()`) (and likewise for `i2cdisplay`). However, this is not necessary, since the `never_reset` flags only take effect at the end of the session, and at that time everything is already handled correctly by the changes made here. There is effectively a redundancy between the `never_reset` flags and `reset_board_busses()` checking for things still in use by displays. Therefore I avoided adding that symmetry, which would just add more code.

Critical review appreciated.

The **third commit** fixes a tangentially related issue: After one had explicitly deinited the `board.SPI` or `board.I2C` busses (maybe to temporarily use their pins for other purposes), there was no way to get them back in the same session. Calling the function again would just return the unusable deinited object. Reproducible as follows:

```
Adafruit CircuitPython 6.0.0-rc.0-99-g32c2e9354-dirty on 2020-10-25; PewPew M4 CW with samd51G19
>>> import board
>>> bus = board.SPI()
>>> bus.try_lock()
True
>>> bus.write(b'X')
>>> bus.unlock()
>>> bus.deinit()
>>> 
>>> bus = board.SPI()
>>> bus.try_lock()
True
>>> bus.write(b'X')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Object has been deinitialized and can no longer be used. Create a new object.
>>> 
```

or

```
# with an SSD1306 display connected to the I2C pins
Adafruit CircuitPython 6.0.0-rc.0-99-g32c2e9354-dirty on 2020-10-25; PewPew M4 CW with samd51G19
>>> import board
>>> bus = board.I2C()
>>> bus.try_lock()
True
>>> bus.writeto(60, b'X')
>>> bus.unlock()
>>> bus.deinit()
>>> 
>>> bus = board.I2C()
>>> bus.try_lock()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Object has been deinitialized and can no longer be used. Create a new object.
>>> 
```

Testing on non-SAMD ports would be appreciated.

2020-10-25 02:35 UTC, jepler reviewed
This looks good to me but I would also like @tannewt to weigh in on the movement of reset_port in particular.  Thank you!

2020-10-25 02:49 UTC, dhalbert approved these changes
Thanks for your careful analysis!

2020-10-25 10:51 UTC, cwalther commented on main.c
> +    reset_port();
Good point, done.

2020-10-26 21:14 UTC, tannewt requested changes
This looks really good to me! I think we'll want this in 6.0.x though and then we can merge 6.0.x into `main`.

2020-10-26 21:15 UTC, tannewt commented
Would you mind rebasing onto 6.0.x and then changing the PR's base? Thanks!

2020-10-26 22:43 UTC, cwalther commented
Done.

2020-10-27 20:52 UTC, tannewt approved these changes
Thank you!

2020-10-27 20:53 UTC, merged

2020-10-27 21:28 UTC, cwalther commented
Thanks!