ESP32S2: Support for RotaryIO
adafruit/circuitpython pull request #3614
Opened 2020-10-27 18:45 UTC by microDev1

2020-10-30 19:10 UTC, tannewt reviewed
This looks really good! Were you able to test it or do you need me to?

2020-10-30 19:10 UTC, tannewt commented on ports/esp32s2/common-hal/rotaryio/IncrementalEncoder.c
> + * Copyright (c) 2018 Scott Shawcroft for Adafruit Industries
Update this for yourself.

2020-11-01 12:45 UTC, microDev1 commented
@tannewt Thanks for the review. I tested this with my [microS2](https://circuitpython.org/board/microdev_micro_s2/) & two different types of encoder.

2020-11-03 00:40 UTC, tannewt requested changes
Don't forget to change the copyright. Let's wait for #3615 to be merged and then update this PR for the pcnt sharing code. Thanks!

2020-11-03 15:37 UTC, hierophect commented
Seconding Scott here - if you can get everything in CountIO moved over to a `peripherals/pcnt.c` file, you can migrate all your init and reset functions over to it, and the two modules will be able to co-exist without accidentally trying to reserve each other's PCNT units. Check out rmt.c for an example - the RMT is used by PulseIn, PulseOut, *and* Neopixel_write, so they all share the same reservation system, init/deinit, and reset_all functions.

2020-11-09 23:41 UTC, tannewt approved these changes
Looks great! Thank you!

2020-11-09 23:41 UTC, merged