Issue3579 - Check for CTRL-C During sleep on esp32s2
adafruit/circuitpython pull request #3647
Opened 2020-11-05 17:22 UTC by DavePutz

This PR is not very elegant. But, in its defense, the following fixes were tried without success:
1) I tried to find a way to interrupt or terminate vTaskDelayUntil(). However, nothing I found was able to do that. Trying to
    do anything about the sleep state during another interrupt handler (such as ticks or usb) generally resulted in either a 
   complete hang or did nothing.
2) The esp32s2 light sleep state was investigated. However, any light sleep past about 1 second resulted in the USB session 
  getting disconnected, which makes getting a CTRL-C in impossible. I did not look at the effect of light sleep on Wifi or BLE, but 
  there is a comment in the code indicating those might be a problem as well.  I did not discover any way to keep the two pins 
  needed for USB alive during light sleep.
3) The sleep interval in the PR (1) was chosen to maintain as accurate a sleep time as possible. Higher values grew increasingly 
   inaccurate for a time.sleep() call.
Any comments and suggestions for improvement are quite welcome.

2020-11-05 19:00 UTC, tannewt commented
I think you could invert the API you need from FreeRTOS. Instead of using a time delay API, use one that is blocked on inter-task flag with a time out. xEventGroupWaitBits is what you'd need I think. https://www.freertos.org/xEventGroupWaitBits.html Then, share a group of event bits with TinyUSB callbacks that can indicate a ctrl-c. Then wait on the event bit while timing out with the sleep time.

2020-11-05 20:21 UTC, DavePutz commented
That sounds like a better fix than a clumsy loop. I will investigate and
see what I can do with the suggestion.

On Thu, Nov 5, 2020 at 1:01 PM Scott Shawcroft <notifications@github.com>
wrote:

> I think you could invert the API you need from FreeRTOS. Instead of using
> a time delay API, use one that is blocked on inter-task flag with a time
> out. xEventGroupWaitBits is what you'd need I think.
> https://www.freertos.org/xEventGroupWaitBits.html Then, share a group of
> event bits with TinyUSB callbacks that can indicate a ctrl-c. Then wait on
> the event bit while timing out with the sleep time.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/circuitpython/pull/3647#issuecomment-722576621>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFNJKEWXTWPWA6KMXC7EUILSOLY7NANCNFSM4TLUXJ5A>
> .
>

2020-11-06 04:46 UTC, DavePutz commented
Reworked the PR to use RTOS task notification instead of a loop.

2020-11-10 00:54 UTC, tannewt requested changes
Thanks @DavePutz! A couple questions and a variable rename suggestion to better separate FreeRTOS APIs from our own.

I suspect we'll need to use this for auto-reload during sleep as well.

2020-11-10 00:54 UTC, tannewt commented on ports/esp32s2/supervisor/usb.c
> +TaskHandle_t xTaskToNotify = NULL;
```suggestion
TaskHandle_t sleeping_circuitpython_task = NULL;
```

2020-11-10 00:54 UTC, tannewt commented on ports/esp32s2/supervisor/port.c
> +      xTaskToNotify = NULL;
```suggestion
      sleeping_circuitpython_task = NULL;
```

2020-11-10 00:54 UTC, tannewt commented on ports/esp32s2/supervisor/port.c
> +BaseType_t notify_wait = 0;
Why do these need to be outside the function?

2020-11-10 00:54 UTC, tannewt commented on ports/esp32s2/supervisor/port.c
> +extern TaskHandle_t xTaskToNotify;
Could this go in `ports/esp32s2/supervisor/port.h`?

```suggestion
extern TaskHandle_t sleeping_circuitpython_task;
```

2020-11-10 00:54 UTC, tannewt commented on ports/esp32s2/supervisor/port.c
> +    xTaskToNotify = xTaskGetCurrentTaskHandle();
```suggestion
    sleeping_circuitpython_task = xTaskGetCurrentTaskHandle();
```

2020-11-10 00:54 UTC, tannewt commented on ports/esp32s2/supervisor/usb.c
> +        if (xTaskToNotify != NULL) {
```suggestion
        // CircuitPython's VM is run in a separate FreeRTOS task from TinyUSB. So, we must notify the
        // other task when a CTRL-C is received.
        if (sleeping_circuitpython_task != NULL) {
```

2020-11-10 00:54 UTC, tannewt commented on ports/esp32s2/supervisor/usb.c
> +          xTaskNotifyGive(xTaskToNotify);
```suggestion
          xTaskNotifyGive(sleeping_circuitpython_task);
```

2020-11-10 18:26 UTC, DavePutz commented
Suggested changes implemented except for moving the extern declare to ports/esp32s2/supervisor/port.h. That file does not exist; is it worth creating it to hold this one line?

2020-11-10 18:28 UTC, tannewt commented
> Suggested changes implemented except for moving the extern declare to ports/esp32s2/supervisor/port.h. That file does not exist; is it worth creating it to hold this one line?

Up to you. I suspect we'll need access to it to fix the auto-reload while sleeping too but that fix might live in these files too.

2020-11-10 18:59 UTC, tannewt approved these changes
Looks good! Thank you!

2020-11-10 19:18 UTC, DavePutz commented
Since you think it may be useful in the future I have split out the extern declare. I did name it ports/esp32s2/supervisor/esp_port.h, however, to avoid naming conflicts with the global supervisor/port.h

2020-11-10 21:09 UTC, tannewt approved these changes
Thanks!

2020-11-10 21:09 UTC, merged