Add new board BastBLE
adafruit/circuitpython pull request #3662
Opened 2020-11-09 19:53 UTC by Soulkrown

Hi
I would like to be able to add this new BastBLE card from electronic cats to your repository.
I await your feedback and response.
I thank you in advance.
Best regards

2020-11-09 23:29 UTC, tannewt requested changes
Please follow up when the CI fails. Thanks! I don't see any other potential issues.

2020-11-09 23:29 UTC, tannewt commented on .github/workflows/build.yml
> +	- "bastBLE"
```suggestion
        - "bastBLE"
```

2020-11-10 18:41 UTC, tannewt commented
I suggest installing pre-commit locally to test more rapidly: https://pre-commit.com/#installation

2020-11-17 21:15 UTC, tannewt commented
The bastble build is broken. Looks like it needs a function name updated: https://github.com/adafruit/circuitpython/pull/3662/checks?check_run_id=1410247014

2020-12-20 22:53 UTC, sabas1080 commented
@tannewt ready, thanks!

2020-12-22 01:39 UTC, tannewt approved these changes
Looks good! One comment that you can make a follow up PR for if you like.

2020-12-22 01:39 UTC, tannewt commented on ports/nrf/boards/bastble/pins.c
> +    { MP_ROM_QSTR(MP_QSTR_VBAT), MP_ROM_PTR(&pin_P0_26)  },
Note, most boards name this pin VOLTAGE_MONITOR or BATTERY.

2020-12-22 01:39 UTC, merged