esp32s2: esp_error: Consistent error checking of esp-idf calls
adafruit/circuitpython pull request #3677
Opened 2020-11-11 18:13 UTC by jepler

I wrote this code for audioio but that's not ready for inclusion, and @microdev1 says it would be useful in their work.

2020-11-11 18:46 UTC, microDev1 commented
Thanks! @jepler. One question, what parameters are you using to categorize an error of type `ESP_ERR_` to be eligible for inclusion.

2020-11-11 23:00 UTC, jepler commented
@microDev1 I think that any error that would plausibly arise from user code we would want to include.  I just did the ones in the "main" error header, **esp_err.h**.

2020-11-12 01:27 UTC, tannewt requested changes
Thanks for this! Would you mind using a subclass of OSError instead of OSError itself? That way we can differentiate a bit more. There is an example with the espidf.MemoryError already.

2020-11-12 01:27 UTC, tannewt commented on ports/esp32s2/esp_error.c
> +            msg = translate("Out of memory");
We have a special subclass of MemoryError for this already: https://github.com/adafruit/circuitpython/blob/main/ports/esp32s2/bindings/espidf/__init__.c#L68

2020-11-12 01:31 UTC, jepler commented
Are you thinking just one additional class for any esp error?  if not, can you let me know what classes you're looking for?

2020-11-12 20:15 UTC, tannewt commented
@jepler Ya, one to start with in addition to the existing MemoryError. We can subclass the IDFError exception in the future if need be.

2021-01-12 22:32 UTC, closed without merging