Add hiibot_iots2.
adafruit/circuitpython pull request #3730
Opened 2020-11-20 02:55 UTC by BradChan

2020-11-24 00:05 UTC, tannewt requested changes
Please fix pre-commit as well as getting your own USB VID/PID. You can automatically fix pre-commit errors by installing it locally: https://pre-commit.com/#installation

2020-11-24 00:05 UTC, tannewt commented on ports/esp32s2/boards/hiibot_iots2/mpconfigboard.mk
> +USB_PID = 0x80E8
0x239A is Adafruit's USB VID. Please change this to one you are allowed to use. If the board is open source, then you can get one from https://pid.codes.

2021-01-20 17:06 UTC, ladyada commented
@BradChan please get a PID from espressif here https://github.com/espressif/usb-pids

2021-02-05 14:15 UTC, dhalbert commented
@BradChan did you get another PID?

2021-06-24 12:27 UTC, dhalbert commented
@BradChan Would you like to finish this off? DId you get a PID?

2021-07-15 19:04 UTC, dhalbert commented
@BradChan Closing for now. Please reopen when you're ready. Thanks!

2021-07-15 19:04 UTC, closed without merging