Fixing microcontroller.cpu on multi-core cpus and adding microcontroller.cpus
adafruit/circuitpython pull request #4087
Opened 2021-01-28 21:52 UTC by DavePutz

This will allow microcontroller.cpu.temperature, etc. to work properly on an RP2040 or other multi-cpu chip. It will default to the values for cpu 0. In addition, it adds  microcontroller.cpus, indexed by cpu number, to allow access to the values for other cpus (for example, microcontroller.cpus[1].voltage)  Note that microcontroller.cpus is only added for chips where CIRCUITPY_PROCESSOR_COUNT is defined to be > 1.

2021-01-29 17:50 UTC, dhalbert requested changes
LGTM. Just a typo to fix.

2021-01-29 17:50 UTC, dhalbert commented on shared-bindings/microcontroller/__init__.c
> +//| (clock frequency) on chips with more than 1 cpu.  the index selects which cpu.
```suggestion
//| (clock frequency) on chips with more than 1 cpu. The index selects which cpu.
```

2021-01-29 17:59 UTC, DavePutz commented on shared-bindings/microcontroller/__init__.c
> +//| (clock frequency) on chips with more than 1 cpu.  the index selects which cpu.
Fixed, thanks!

2021-02-01 17:50 UTC, dhalbert approved these changes
Looks good! Thanks!

2021-02-01 17:50 UTC, merged