Update StateMachine.c
adafruit/circuitpython pull request #4276
Opened 2021-02-26 23:08 UTC by bergdahl

Changed wording to use "max" instead

2021-03-01 22:28 UTC, dhalbert reviewed
@bergdahl Are you requesting this change to make both it and your translation shorter? I have been advocating use comparison operators like `In-buffer elements must be <= 4 bytes long` for brevity, but I don't know how easily that translates.

2021-03-02 11:25 UTC, bergdahl commented
I don't see a problem expressing the error the same way you would express them in the language itself
(Scott merged this pull request together with the fix of his strings in the last live stream).

2021-03-02 16:52 UTC, tannewt commented
I didn't merge this during my stream. I only ran `make translate`. (See: https://github.com/adafruit/circuitpython/blob/main/locale/circuitpython.pot#L1089 is the original) @dhalbert do you want to update this PR with the rewording?

2021-03-02 17:01 UTC, dhalbert requested changes
OK, I will make these changes in the web interface, and will then push a `make translate`.

2021-03-02 17:01 UTC, dhalbert commented on ports/raspberrypi/bindings/rp2pio/StateMachine.c
> +        mp_raise_ValueError(translate("Out buffer elements must be max 4 bytes long"));
```suggestion
        mp_raise_ValueError(translate("Out-buffer elements must be <= 4 bytes long"));
```

2021-03-02 22:11 UTC, dhalbert approved these changes

2021-03-02 22:11 UTC, merged