[stm] implementation of audiopwmio
adafruit/circuitpython pull request #4399
Opened 2021-03-13 17:02 UTC by tyomitch

Based on nrf PWMAudioOut by @jepler and stm PulseOut by @hierophect

Tested on a Meowbit

2021-03-19 20:53 UTC, hierophect requested changes
Thanks for this PR! I'm unable to get this working on my Meowbit with the WAV sample code in the [Circuitpython documentation](https://circuitpython.readthedocs.io/en/latest/shared-bindings/audiopwmio/index.html). The speaker makes a little strangled sound, and then the program hangs irrecoverably, requiring a manual erase of the entire flash. If you have a test sketch of your own, I'm happy to try that.

The style and timer allocation stuff looks generally ok, I can't point out where the hang might be at first glance. There are also some minor things to fix unrelated to performance.

2021-03-19 20:53 UTC, hierophect commented on ports/stm/common-hal/microcontroller/Pin.c
> +void set_drive_mode(const mcu_pin_obj_t *pin, uint32_t mode) {
This should be a static function within PWMAudioOut.c, it doesn't need to be in Pin.c. The function in DigitalIO is very old and shouldn't be adjusting the pull and speed as it does, so it needs to be tweaked anyway.

2021-03-19 20:53 UTC, hierophect commented on ports/stm/common-hal/digitalio/DigitalInOut.c
> +    set_drive_mode(self->pin, drive_mode == DRIVE_MODE_OPEN_DRAIN ?
Please revert this as per the previous comment. This module needs some reworks, and Pin.c isn't a good place to abstract this kind of thing in the meantime.

2021-03-19 20:53 UTC, hierophect commented on ports/stm/common-hal/audiopwmio/PWMAudioOut.c
> + * Copyright (c) 2021 Artyom Skrobov for Adafruit Industries
We use "for Adafruit Industries" to designate work that was sponsored by Adafruit, so you don't have to include it in your byline.

2021-03-19 21:30 UTC, tyomitch commented
@hierophect thank you for the review!

> I'm unable to get this working on my Meowbit with the WAV sample code in the [Circuitpython documentation](https://circuitpython.readthedocs.io/en/latest/shared-bindings/audiopwmio/index.html). The speaker makes a little strangled sound, and then the program hangs irrecoverably, requiring a manual erase of the entire flash. If you have a test sketch of your own, I'm happy to try that.

My guess is that it's #4397 :-)
You should be able to get `WaveFile`s playing if you prepend the call to `play()` with a small `time.sleep()`, so that the screen is no longer updating at the time `PWMAudioOut` tries to access the flash.
The PR replaces the irrecoverable hang with a recoverable failure, so it would simplify testing, but it still wouldn't allow accessing flash in parallel with updating the screen.

`RawSample`s should be playing OK regardless of the SPI locking issue.

2021-03-19 21:59 UTC, hierophect commented
@tyomitch ah, thanks for the full context, that probably is it. I'll make a note of my problem for Scott in the issue.

2021-03-27 17:25 UTC, hierophect commented
@tyomitch thanks for the updates. Just a gentle note that here on the Circuitpython github, our general policy is to update PRs without force-pushing, so we can see what you've edited and the comments are not lost. It makes it easier to tell when re-testing with hardware is necessary. Is this ready for another review?

2021-03-27 23:31 UTC, tyomitch commented
> Is this ready for another review?

Yes please :)

I will try to avoid force-pushing PRs, but for the record, overwritten commits are not lost, and you can see the changes since the first review at https://github.com/adafruit/circuitpython/compare/fc9b42a..b40d072 -- inevitably very noisy because of an intervening global reformatting (a52eb88)

2021-04-05 22:35 UTC, hierophect approved these changes
Tested on Meowbit and Feather, looks good to me!

2021-04-05 22:35 UTC, merged