added board configuration for Sparkfun ThingPlus RP2040
adafruit/circuitpython pull request #4411
Opened 2021-03-15 14:33 UTC by mintakka

Added board configuration files for the [Sparkfun ThingPlus RP2040](https://learn.sparkfun.com/tutorials/rp2040-thing-plus-hookup-guide/hardware-overview)

Builtin NeoPixel, LED, QWIIC port and build-in micro-SD slot all tested and working with the updated pin definitions.

2021-03-15 22:25 UTC, falkenad commented
@mintakka Shouldn't the flash size be 16 as they're 25Q128 flash chips?
IE: #define TOTAL_FLASH_SIZE 8 * 1024 * 1024
Should be:
#define TOTAL_FLASH_SIZE 16 * 1024 * 1024  ?

2021-03-15 22:31 UTC, mintakka commented
Yes it should be, I missed that!

On Mon, Mar 15, 2021 at 6:26 PM falkenad ***@***.***> wrote:

> @mintakka <https://github.com/mintakka> Shouldn't the flash size be 16 as
> they're 25Q128 flash chips?
> IE: #define TOTAL_FLASH_SIZE 8 * 1024 * 1024
> Should be:
> #define TOTAL_FLASH_SIZE 16 * 1024 * 1024 ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/circuitpython/pull/4411#issuecomment-799795954>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACNXKRIJTXTKHLKNTBDQGELTD2CPRANCNFSM4ZGVMNRA>
> .
>

2021-03-16 00:43 UTC, tannewt requested changes
Thanks for the definition! Please rename the folder to `sparkfun_thingplus_rp2040` because thingplus is a name used for the form factor. You'll also need to add the board to .github/workflows/build.yml

2021-03-16 00:43 UTC, tannewt commented on ports/raspberrypi/boards/sparkfun_thingplus/mpconfigboard.h
> +// Flash chip is GD25Q64 connected over QSPI
```suggestion
// Flash chip is GD25Q128 connected over QSPI
```

2021-03-16 00:43 UTC, tannewt commented on ports/raspberrypi/boards/sparkfun_thingplus/mpconfigboard.mk
> +USB_PID = 0x80F2
```suggestion
USB_VID = 0x1B4F
USB_PID = 0x0025
```

2021-03-16 00:59 UTC, mintakka commented
Thank you, I will make these changes and re-submit

On Mon, Mar 15, 2021 at 8:43 PM Scott Shawcroft ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for the definition! Please rename the folder to
> sparkfun_thingplus_rp2040 because thingplus is a name used for the form
> factor. You'll also need to add the board to .github/workflows/build.yml
> ------------------------------
>
> In ports/raspberrypi/boards/sparkfun_thingplus/mpconfigboard.h
> <https://github.com/adafruit/circuitpython/pull/4411#discussion_r594783115>
> :
>
> > +#define MICROPY_HW_BOARD_NAME "Sparkfun ThingPlus RP2040"
>
> +#define MICROPY_HW_MCU_NAME "rp2040"
>
> +
>
> +#define MICROPY_HW_NEOPIXEL (&pin_GPIO8)
>
> +
>
> +#define DEFAULT_I2C_BUS_SCL (&pin_GPIO7)
>
> +#define DEFAULT_I2C_BUS_SDA (&pin_GPIO6)
>
> +
>
> +#define DEFAULT_SPI_BUS_SCK (&pin_GPIO14)
>
> +#define DEFAULT_SPI_BUS_MOSI (&pin_GPIO15)
>
> +#define DEFAULT_SPI_BUS_MISO (&pin_GPIO12)
>
> +
>
> +#define DEFAULT_UART_BUS_RX (&pin_GPIO1)
>
> +#define DEFAULT_UART_BUS_TX (&pin_GPIO0)
>
> +
>
> +// Flash chip is GD25Q64 connected over QSPI
>
>
> ⬇️ Suggested change
>
> -// Flash chip is GD25Q64 connected over QSPI
>
> +// Flash chip is GD25Q128 connected over QSPI
>
>
> ------------------------------
>
> In ports/raspberrypi/boards/sparkfun_thingplus/mpconfigboard.mk
> <https://github.com/adafruit/circuitpython/pull/4411#discussion_r594784116>
> :
>
> > +USB_VID = 0x239A
>
> +USB_PID = 0x80F2
>
>
> ⬇️ Suggested change
>
> -USB_VID = 0x239A
>
> -USB_PID = 0x80F2
>
> +USB_VID = 0x1B4F
>
> +USB_PID = 0x0025
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/circuitpython/pull/4411#pullrequestreview-612763415>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACNXKRIBBESDAIFXJ4L67TTTD2ST7ANCNFSM4ZGVMNRA>
> .
>

2021-03-16 03:03 UTC, mintakka reviewed
revised pull request with requested changes

2021-03-16 15:57 UTC, mintakka commented
@tannewt - I've addressed the required changes and I think it is ready for re-review

2021-03-16 17:36 UTC, tannewt requested changes
A few minor things. Sorry I didn't see them in the first round of reviewing.

2021-03-16 17:36 UTC, tannewt commented on .github/workflows/build.yml
> +        - "sparkfun_thingplus_rp2040"
```suggestion
        - "sparkfun_thing_plus_rp2040"
```

2021-03-16 17:36 UTC, tannewt commented on ports/raspberrypi/boards/sparkfun_thingplus_rp2040/mpconfigboard.mk
> +USB_MANUFACTURER = "Sparkfun"
```suggestion
USB_MANUFACTURER = "SparkFun"
```

2021-03-16 17:36 UTC, tannewt commented on ports/raspberrypi/boards/sparkfun_thingplus_rp2040/mpconfigboard.h
> +#define MICROPY_HW_BOARD_NAME "Sparkfun ThingPlus RP2040"
```suggestion
#define MICROPY_HW_BOARD_NAME "SparkFun Thing Plus - RP2040"
```

2021-03-16 17:48 UTC, mintakka reviewed
All change requests incorporated

2021-03-16 17:48 UTC, mintakka commented
Those are great catches, thanks!

2021-03-17 01:11 UTC, mintakka reviewed
aligned board name in boards.yml with the folder name for the board in ports/raspberrypi/boards

2021-03-17 21:02 UTC, mintakka commented
Alright, looks like the build checks all passed now. I think this is ready for review.

2021-03-17 21:22 UTC, jepler approved these changes
Thank you!  Github tells me this is your first pull request to any repo, congratulations on that as well.

2021-03-17 21:23 UTC, merged

2021-03-17 21:49 UTC, mintakka commented
awesome, thanks!