Add board definition for Sparkfun Pro Micro RP2040
adafruit/circuitpython pull request #4419
Opened 2021-03-16 04:16 UTC by spe2

Adds appropriate board definition files for the Pro Micro RP2040 and adds it to the build.yml file.

2021-03-16 17:39 UTC, tannewt requested changes
Two minor capitalization changes. Good otherwise. Thank you!

2021-03-16 17:39 UTC, tannewt commented on ports/raspberrypi/boards/sparkfun_pro_micro_rp2040/mpconfigboard.h
> +#define MICROPY_HW_BOARD_NAME "Sparkfun Pro Micro RP2040"
```suggestion
#define MICROPY_HW_BOARD_NAME "SparkFun Pro Micro RP2040"
```

2021-03-16 17:39 UTC, tannewt commented on ports/raspberrypi/boards/sparkfun_pro_micro_rp2040/mpconfigboard.mk
> +USB_MANUFACTURER = "Sparkfun"
```suggestion
USB_MANUFACTURER = "SparkFun"
```

2021-03-16 17:55 UTC, spe2 commented
@tannewt Suggested changes committed, thanks.

2021-03-18 01:17 UTC, tannewt approved these changes
Thanks!

2021-03-18 01:17 UTC, merged