Add Artisense RD00 board files
adafruit/circuitpython pull request #4512
Opened 2021-03-30 09:10 UTC by m-byte

VID/PID as assigned by Espressif (see https://github.com/espressif/usb-pids)

2021-03-30 13:32 UTC, jepler requested changes
Thank you!  I saw some small items to correct.

2021-03-30 13:32 UTC, jepler commented on ports/esp32s2/boards/artisense_rd00/board.c
> + * Copyright (c) 2020 Scott Shawcroft for Adafruit Industries
Please update these files with your own copyright information.  E.g., "Copyright (c) 2021 <your name>", adding "for <company name>" if applicable.

2021-03-30 13:32 UTC, jepler commented on ports/esp32s2/boards/artisense_rd00/mpconfigboard.h
> + * Copyright (c) 2019 Scott Shawcroft for Adafruit Industries
here as well

2021-04-03 23:40 UTC, jepler approved these changes
Thank you!  This looks OK to merge if the CI passes.

2021-04-03 23:40 UTC, merged

2021-07-26 20:24 UTC, dhalbert commented
@m-byte Hi - This board doesn't look like it's been added to circuitpython.org yet. If I'm wrong, sorry, otherwise please submit a PR to https://github.com/adafruit/circuitpython-org. If you are not going to produce this board, let us know, thanks.