WIP: Implement 'ParallelImageCapture' for samd51
adafruit/circuitpython pull request #4635
Opened 2021-04-19 14:14 UTC by jepler

This work-in-progress code, together with a WIP CircuitPython library, can successfully capture small (80x60) frames from an OV7670 camera on a Metro M4 GrandCentral.

TODO:
- [ ] a name everyone can agree on
- [ ] capture using DMA, rather than having interrupts disabled for 30ms

![cap](https://user-images.githubusercontent.com/1517291/115250947-ac1ad680-a0ef-11eb-914c-4e665df2f040.png)

2021-04-19 22:24 UTC, tannewt reviewed
Thanks for the module rename. I like `imagecapture`. Just a couple other minor things.

I think you need per-param comments for the constructor too.

2021-04-19 22:24 UTC, tannewt commented on shared-bindings/imagecapture/ParallelImageCapture.c
> +//|         hsync: Optional[microcontroller.Pin],
Should this be HREF instead of HSYNC?

2021-04-19 22:24 UTC, tannewt commented on locale/circuitpython.pot
> +msgid "PCC_D%d in use"
Please make this a generic message. PCC is SAMD specific.

2021-04-20 18:55 UTC, jepler commented
@tannewt this is ready for a fresh review.

Main question **I** have right now is, I used "audio_dma" channels. As far as I can see this will work just fine (but didn't test): with 3 channels you can play stereo audio in the background and capture a framebuffer image in the foreground; we'd have to increase the channel count in the future when we enable this or audio capture to also happen in the background.  That said, should the APIs `audio_dma_allocate_channel()` and `audio_dma_free_channel` be renamed?  Be moved to different locations?  Or can it be left as-is?

2021-04-21 23:50 UTC, tannewt requested changes
I think it would be good to rename the audio_dma stuff. I'm trying to remember what makes those special so we could rename them that way. Is it that they can be triggered by events?

2021-04-21 23:50 UTC, tannewt commented on shared-bindings/displayio/ColorConverter.c
>  // TODO(tannewt): Add support for other color formats.
Delete this and add a docstring for it.

2021-04-21 23:50 UTC, tannewt commented on shared-bindings/displayio/__init__.c
> +//|     """The standard 16-bit colorspace"""
Please elaborate on these comments so that no other reference info is needed.

2021-04-21 23:50 UTC, tannewt commented on shared-bindings/displayio/__init__.c
> +//|     """The standard 16-bit colorspace"""
Please elaborate on these comments so that no other reference info is needed.

2021-04-23 14:58 UTC, jepler commented
@tannewt this is ready for a fresh review assuming the CI passes.  Let me know if I need to merge main or rebase onto it.

2021-04-23 16:50 UTC, tannewt approved these changes
Code looks good. Thank you! You'll need to fix the CI though.

2021-04-23 20:31 UTC, tannewt approved these changes
Thank you!

2021-04-23 20:31 UTC, merged

2021-04-24 14:37 UTC, jepler commented
@ladyada 
Test program for ov7670 + gcm4 + 1.8" tft shield: https://gist.github.com/645f7d052b63103111b011e507df38a1
Test program for ov7670 + rpi pico + 2.0" ST7789 breakout: https://gist.github.com/f357464e194a4ba85bbcd43378b1e189

I think the 2nd one needs the fix for the DIV2 resolution mode, https://github.com/adafruit/Adafruit_CircuitPython_OV7670/pull/4