Merge 1.16
adafruit/circuitpython pull request #4897
Opened 2021-06-18 15:54 UTC by jepler

2021-06-18 15:55 UTC, jepler commented
Unix tests pass locally, I'll let CI chew on the rest and see where we're at.

2021-06-21 23:14 UTC, tannewt requested changes
Thanks for taking on this merge!

Please delete `ports/zephyr`, `ports/rp2`, `ports/esp32` and `ports/esp8266`. We have our own ports and the extra folders confuse folks.

I delete `tests/multi_{net,bluetooth}` too since we don't use it.

We may want to delete `tools/mpremote` as well. I don't think it'll work with CircuitPython and I doubt we want to support it.

2021-06-21 23:14 UTC, tannewt commented on tools/pyboard.py
> +# SPDX-FileCopyrightText: Copyright (c) 2014-2016 Damien P. George
```suggestion
# SPDX-FileCopyrightText: Copyright (c) 2014-2021 Damien P. George
```

And delete the chunk below.

2021-06-22 00:52 UTC, jepler commented
@tannewt OK, got those all I think.  Do you want me to try to "squash" this to a single merge commit, or did your recent experiences lead you to think that's not such a good idea?

2021-06-22 18:52 UTC, tannewt commented
No need to squash. It's funny with merge commits.

I see a `ports/qemu-arm` left that I forgot to list. For reference, I used this script to delete other ports: https://github.com/adafruit/circuitpython/blob/main/tools/merge_micropython.py#L13

2021-06-23 17:14 UTC, tannewt approved these changes
Looks great! Thank you!

2021-06-23 17:15 UTC, merged

2021-06-23 17:16 UTC, ladyada commented
woo hoo!