Add traceback module
adafruit/circuitpython pull request #5072
Opened 2021-07-27 18:36 UTC by microDev1

This PR implements `CPython` compatible `traceback` module.

2021-07-27 18:59 UTC, microDev1 commented
- Only `print_exception()` is currently implemented. I was considering implementing `format_exception()` (only difference is that this returns a string) but ran into trouble with compressed strings `%q` specifier. I am thinking of adding `mp_sprintf()` but haven't made any progress on that front yet.
- Following args are ignored for the reasons given and are only implemented to maintain compatibility with `CPython`.
  - `etype` - From `Python-3.5` this is ignored and is inferred from type of value internally.
  - `tb` - The `__traceback__` object is not exposed at the moment and is obtained internally; however, if set to `None`, traceback will not be printed, similar to `CPython`.
  - `chain` - Chained exceptions are not yet implemented.

2021-07-28 15:35 UTC, tannewt commented
>   * `tb` - The `__traceback__` object is not exposed and is obtained internally;
>       however, if this is set to `None`, traceback will not be printed, similar to `CPython`.

Is this parameter required in CPython? What will we provide in CircuitPython? Does it do the same thing in CPython? Would you mind providingn an example use?

2021-07-28 16:59 UTC, microDev1 commented
> Is this parameter required in CPython?

Yes, this is a required parameter.

> What will we provide in CircuitPython? 

As this is ignored, anything (i.e. `Type: Any`) can be supplied to the function call.

> Does it do the same thing in CPython?

Yes, the current implementation is same as in `CPython`. The only difference is:

- `CPython` - The traceback is obtained from the supplied traceback object.
- `CircuitPython` - There is no traceback object (i.e. `Type: TracebackType`) implemented so this is obtained internally.

Only thing I can think of that won't be possible because of the above is supplying traceback from a different exception.

> Would you mind providing an example use?

```python
try:
    raise Exception("xyz")
except Exception as exc:
    # CPython:
    traceback.print_exception(None, exc, None)
    traceback.print_exception(None, exc, exc.__traceback__)
    traceback.print_exception(None, exc, exc.__traceback__, limit=1, file=log, chain=True)
    # CircuitPython:
    traceback.print_exception(None, exc, None)
    traceback.print_exception(None, exc, "any")
    traceback.print_exception(None, exc, "any", limit=1, file=log, chain=True)
   # Output is same in all the cases.
```

2021-07-28 17:02 UTC, microDev1 commented
> Is this parameter required in CPython?

Yes, this is a required parameter.

> What will we provide in CircuitPython? 

As this is ignored, anything (i.e. `Type: Any`) can be supplied to the function call.

> Does it do the same thing in CPython?

Yes, the current implementation is same as in `CPython`. The only difference is:

- `CPython` - The traceback is obtained from the supplied traceback object.
- `CircuitPython` - There is no traceback object (i.e. `Type: TracebackType`) implemented so this is obtained internally.

Only thing I can think of that won't be possible because of the above is supplying traceback from a different exception.

> Would you mind providing an example use?

```python
try:
    raise Exception("xyz")
except Exception as exc:
    # CPython:
    traceback.print_exception(None, exc, None)
    traceback.print_exception(None, exc, exc.__traceback__)
    traceback.print_exception(None, exc, exc.__traceback__, limit=1, file=log, chain=True)
    # CircuitPython:
    traceback.print_exception(None, exc, None)
    traceback.print_exception(None, exc, "any")
    traceback.print_exception(None, exc, "any", limit=1, file=log, chain=True)
    # Output is same in all the cases to there CPython counterpart.
```

2021-07-28 17:18 UTC, microDev1 commented
I can enable `__traceback__` and make it return `0` for now, this will make function calls exactly the same.

2021-07-29 17:47 UTC, tannewt commented
Why don't we make an empty Traceback object type and every exception can have its own. That way we can verify that the given `__traceback__` is from the provided exception. I want to avoid cases where folks can provide values that are invalid in CPython.

2021-08-04 17:47 UTC, tannewt requested changes
Just a couple of things. This is getting closer and closer. Thanks for taking it on!

2021-08-04 17:47 UTC, tannewt commented on shared-bindings/traceback/__init__.c
> +//|     :param bool chain: If `True` then chained exceptions will be printed.
I'd just comment this here that it isn't implemented.

2021-08-04 17:47 UTC, tannewt commented on shared-bindings/traceback/__init__.c
> +
Please put everything below in shared-module. It's easier to read shared bindings if it only does argument validation.

2021-08-06 19:10 UTC, tannewt approved these changes
Thank you!

2021-08-06 19:10 UTC, merged