Lolin S2 Mini - remove NeoPixel, pin assignments to match Wemos
adafruit/circuitpython pull request #5297
Opened 2021-09-03 16:21 UTC by durapensa

Wemos/Lolin's MicroPython pin assignments for this board, plus pin assignments from Wemos D1 Mini board (S2 Mini is supposed to retain some shield compatibility with D1 Mini). Also, ESP32-S2 has hardware LED_PWM.

2021-09-03 18:40 UTC, tannewt requested changes
Thanks for these updates. Just added suggestions to delete the things you commented out. No need to have them since they'll never be added.

2021-09-03 18:40 UTC, tannewt commented on ports/esp32s2/boards/lolin_s2_mini/mpconfigboard.h
> +// #define CIRCUITPY_STATUS_LED_POWER (&pin_GPIO15)
```suggestion
```

2021-09-03 18:40 UTC, tannewt commented on ports/esp32s2/boards/lolin_s2_mini/mpconfigboard.h
> +// #define DEFAULT_UART_BUS_TX (&pin_GPIO43) // no UART pins on S2 Mini
```suggestion
```

2021-09-03 18:40 UTC, tannewt commented on ports/esp32s2/boards/lolin_s2_mini/mpconfigboard.mk
> +# CIRCUITPY_BITBANG_NEOPIXEL = 1 # no NeoPixel on S2 Mini
```suggestion
```

2021-09-04 18:34 UTC, microDev1 commented
Reverted a commit adding `board_id`, since it is now set using a macro.

2021-09-07 21:10 UTC, tannewt approved these changes
Thanks for the updates! Looks good to me.

2021-09-07 21:11 UTC, merged