Add rainbowio
adafruit/circuitpython pull request #5534
Opened 2021-11-01 17:23 UTC by jepler

We had rainbowio disabled on some boards.  Try to reenable it, and see if some fit right now.

2021-11-01 19:07 UTC, dhalbert requested changes
Thanks for trying some of these. The simmel is a special-purpose nRF contact-tracing board, so everything irrelevant was turned off. So I'd say just do the sensebox_mcu

2021-11-02 13:06 UTC, jepler commented
@kattni what do you think? this "simmel" board doesn't have a neopixel built in nor is it intended that anyone would add one on.

2021-11-02 14:49 UTC, kattni commented
@jepler If there's _definitely_ no reason to use RGB LEDs with the simmel board, then I agree, it's probably not worth including. That leaves that space available for future modules that make more sense for it.

2021-11-03 01:57 UTC, dhalbert approved these changes

2021-11-03 01:57 UTC, merged