Initial broadcom port for Raspberry Pi
adafruit/circuitpython pull request #5610
Opened 2021-11-22 23:08 UTC by tannewt

This targets the 64-bit CPU Raspberry Pis. The BCM2711 on the Pi 4
and the BCM2837 on the Pi 3 and Zero 2W. There are 64-bit fixes
outside of the ports directory for it.

There are a couple other cleanups that were incidental:
* Use const mcu_pin_obj_t instead of omitting the const. The structs
  themselves are const because they are in ROM.
* Use PTR <-> OBJ conversions in more places. They were found when
  mp_obj_t was set to an integer type rather than pointer.
* Optimize submodule checkout because the Pi submodules are heavy
  and unnecessary for the vast majority of builds.

Fixes #4314

2021-11-22 23:11 UTC, tannewt commented
These are temporary USB PIDs under the Raspberry Pi VID. I'm waiting to hear from @ghollingworth about the official values.

2021-11-22 23:19 UTC, jepler commented on shared-module/displayio/Bitmap.h
> -    size_t *data;
I agree with this change

2021-11-23 19:01 UTC, dhalbert requested changes
Amazing work! Lots of good cleanup removing 32-bit assumptions.

2021-11-24 00:03 UTC, tannewt commented on ports/broadcom/boards/raspberrypi_zero2w/pins.c
> +    { MP_ROM_QSTR(MP_QSTR_GPIO21), MP_ROM_PTR(&pin_GPIO21) },
I just hadn't copied them over. All of the pinouts for the official boards are essentially the same.

2021-11-24 00:07 UTC, tannewt commented on py/enum.h
> +        .locals_dict = (mp_obj_dict_t *)&typename##_locals_dict, \
It only warns when mp_obj_t isn't a pointer type. (I had tried repr D before realizing it was weird 64 bits on 32 bit platform.)

2021-11-24 00:40 UTC, tannewt commented on ports/broadcom/common-hal/microcontroller/__init__.h
> +#define TOTAL_GPIO_COUNT 10
Look like it's for the microcontroller.pin array.

2021-11-24 01:00 UTC, tannewt commented on ports/broadcom/common-hal/busio/UART.c
> +#define NUM_UARTS 2
Added a comment. All of the other uarts are a different peripheral type that isn't handled yet.

2021-11-24 01:24 UTC, tannewt commented
Ok, I've pushed a new version. It includes I2C support too.

2021-11-24 01:42 UTC, dhalbert commented
Thanks for the updates, and hurrah for I2C! zero2w port is failing for some compilation reason, but the pi4b is working.

2021-11-24 14:44 UTC, dhalbert commented
> Thanks for the updates, and hurrah for I2C! zero2w port is failing for some compilation reason, but the pi4b is working.

Looks like a simple fix: I added a `#include`. If this works I will merge.

2021-11-24 14:50 UTC, dhalbert commented
@tannewt Making a commit from the GitHub web interface seems to have upset the build cloning optimizations you added. From https://github.com/adafruit/circuitpython/runs/4313459204?check_suite_focus=true:

```
Run git describe --dirty --tags
  git describe --dirty --tags
  echo >>$GITHUB_ENV CP_VERSION=$(git describe --dirty --tags)
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
fatal: No tags can describe 'e98223cbae0c9dfe636badcc49bb85fa3f905cfa'.
Try --always, or create some tags.
Error: Process completed with exit code 128.
```

2021-11-24 15:03 UTC, dhalbert commented
@tannewt I pushed an empty commit from your repo, and it didn't fix the problem. Hmm.

2021-11-25 00:02 UTC, dhalbert approved these changes

2021-11-25 00:02 UTC, merged