SSL improvements
adafruit/circuitpython pull request #5716
Opened 2021-12-14 01:09 UTC by timhawes

Documentation fixed for wrap_socket (indentation to place it under the correct class, and added the self argument).

SSLContext.wrap_socket now accepts server_hostname=None (the default value). This previously returned an error (TypeError: Can't convert 'NoneType' object to str implicitly).

Implemented the server_hostname argument which was previously ignored. This is done by giving the SSLSocket it's own copy of the ESP-TLS config structure so that we can set the common_name value within it.

Implemented the check_hostname property, load_verify_locations() and set_default_verify_paths() methods on SSLContext. These are based on the documented CPython interfaces.

2021-12-14 06:53 UTC, ladyada commented
thanks! :)

2021-12-14 13:49 UTC, gregoberfield approved these changes
Looks good to me, adding in the SSL Context functions.

2021-12-14 18:46 UTC, tannewt requested changes
Two minor suggestions. Thanks for following the CPython API!

2021-12-14 18:46 UTC, tannewt commented on ports/espressif/common-hal/ssl/SSLContext.c
> +    }
```suggestion
    return !self->ssl_config.skip_common_name;
```

2021-12-14 18:46 UTC, tannewt commented on ports/espressif/common-hal/ssl/SSLContext.c
> +    }
```suggestion
    self->ssl_config.skip_common_name = !value;
```

2021-12-15 18:52 UTC, tannewt approved these changes
Thank you!

2021-12-15 18:52 UTC, merged