shared runtime: Improve buffer handling
adafruit/circuitpython pull request #5781
Opened 2021-12-27 03:11 UTC by jepler

This simplifies the pair of calls mp_get_buffer_raise + normalize_buffer_bounds into a single call. It also lays the groundwork for the element size to be used in normalization, so that e.g., if you work with an array of 16-bit values, `write(buf, start=3, end=9)`
will work in 2 byte chunks, just like `write(buf[3:9])`.

However, the latter part of the change is not enabled yet, it's just that the place it would need to be done is centralized by this change.

This change also saves 104 bytes on trinket m0, which is nice.

As of the time the PR was opened, it's only tested to compile (for feather rp2040 and trinket m0), I didn't run it.

2021-12-27 03:11 UTC, jepler commented
Related: #4988

2021-12-28 15:37 UTC, dhalbert commented
@jepler Could you test this on some different builds? Thanks.

2021-12-29 14:39 UTC, jepler commented
Testing on a feather m4 with busio spi. I placed a jumper wire between MOSI and MISO.

Before the change:
```python
Adafruit CircuitPython 7.1.0-beta.0-153-g27e8a16bf-dirty on 2021-12-01; Adafruit Feather M4 Express with samd51j19
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
bytearray(b'0123456789:;<=>?') bytearray(b'0000000000000000')
bytearray(b'0123456789:;<=>?') bytearray(b'0000000340000000')
```

After the change:
```python
bytearray(b'0123456789:;<=>?') bytearray(b'0000000000000000')
bytearray(b'0123456789:;<=>?') bytearray(b'0000000340000000')
```
```

2022-01-14 20:30 UTC, tannewt requested changes
I don't think this will work for non-zero start values.

2022-01-14 20:30 UTC, tannewt commented on shared/runtime/buffer_helper.c
> +        bufinfo->len = end - start;
Shouldn't this mutate `->buf` too to account for start?

2022-02-13 17:48 UTC, closed without merging