Add BLE scanning for S3 and C3.
adafruit/circuitpython pull request #5927
Opened 2022-01-26 00:34 UTC by tannewt

Everything else should raise NotImplementedError.

First step in #5926

2022-01-26 02:36 UTC, DavePutz commented
Tested on ESP32-S3. Advertisement worked fine, connect did throw a NotImplementedError. So, patch looks good to me.

2022-01-26 04:56 UTC, dhalbert reviewed
This looks like it is coming along nicely! TI did not test yet.

I think it would be good to add `// TODO` on every routine that needs implementation, or needs more implementation. That will help us spot what remains to redo.

2022-01-26 13:22 UTC, microDev1 commented
`esp-idf` was updated recently, a merge from `main` should fix the CI.

2022-01-26 18:33 UTC, tannewt commented
> This looks like it is coming along nicely! I did not test yet.
> 
> I think it would be good to add `// TODO` on every routine that needs implementation, or needs more implementation. That will help us spot what remains to redo.

My plan was to search for `NotImplementedError`. Is that enough?

2022-01-26 20:01 UTC, dhalbert requested changes
I marked some places that should be flagged as NYI.

Also you can add yourself to the copyright on a bunch of files that you're doing a rewrite on,

2022-01-26 20:01 UTC, dhalbert commented on ports/espressif/common-hal/_bleio/PacketBuffer.c
> +}
add `// TODO` or raise `NotImplementedError` (if there's anything to do)

2022-01-26 20:02 UTC, dhalbert commented
> My plan was to search for `NotImplementedError`. Is that enough?

There are some other places too I marked.

2022-01-27 00:46 UTC, tannewt commented
Ah, I didn't do a bunch of functions because I just did the construct method. Will add a bunch of TODOs for those spots.

2022-01-27 18:01 UTC, tannewt commented
Ok @dhalbert, this is ready for a re-review and passes CI.

2022-01-27 18:05 UTC, dhalbert approved these changes
Great -- thanks!

2022-01-27 18:05 UTC, merged