Enable mdns hostname setting
adafruit/circuitpython pull request #5979
Opened 2022-02-03 15:57 UTC by jepler

Having done this, I can
```
wifi.radio.connect(...)
wifi.radio.mdns_hostname("qtpy")
```

and then on my desktop computer I can `ping qtpy.local`.  This will also be useful when using wifi boards as http servers, since they could be reached by name rather than by IP address on systems that support mdns.

A second step may be to add support for [mdns services](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/protocols/mdns.html#_CPPv416mdns_service_addPKcPKcPKc8uint16_tA_15mdns_txt_item_t6size_t), which for instance allow a device to publish that it is a webserver, file server, printer, etc.

2022-02-03 16:32 UTC, anecdata reviewed
Nice feature!

Perhaps clarify the [distinction](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/mdns.html) between hostname and instance name for the docs.

2022-02-03 18:21 UTC, tannewt requested changes
Is this something that we can expect from all wifi instances? Could we provide it ourselves on top of other network interfaces? Maybe it'd be better to have a separate module and API for it.

I worry that by putting it in Radio you are suggesting all implementations of the radio API should have it.

2022-02-04 03:24 UTC, jepler commented
While it's possible we might use a different device with a TCP/IP stack that doesn't support mdns, it would be possible to have these properties always return None and error if a non-None value is ever assigned.

I could remove the "instance name" for now, it is more useful when your device has an "mdns service". In this case, the "friendly name" (instance name) can be shown in the service browser. For example, in the `avahi-browse -a` output line like
```
+ enp8s0 IPv4 OctoPrint instance on octopi                  Web Site             local
```
the string "OctoPrint instance on octopi" is (I believe) the "instance name".

2022-02-04 03:24 UTC, jepler commented
One build failure was a network problem, the other is an atmel-samd build that is out of space in the russian translation. Did the main branch not encounter that problem?

2022-02-04 03:27 UTC, dhalbert commented
> the other is an atmel-samd build that is out of space in the russian translation. Did the main branch not encounter that problem?

I fixed that in #5981, since it kept showing up.

2022-02-04 14:55 UTC, jepler commented
@tannewt I clarified the documentation to state that if the networking stack doesn't support mdns then
 * the value of the property is always None
 * setting it to a non-None value will raise a ValueError

does this allay your concerns about a future networking stack that doesn't support mdns, or do you still want this in a separate module?  If a separate module, would you care to suggest a name? Here are the first two alternatives that came to mind for me:
```python
import mdns
import wifi

mdns.set_hostname(wifi.radio, "qtpy")
```

```python
from mdns import Mdns
import wifi
m = Mdns(radio)
m.hostname = "qtpy"
```

@anecdata I improved the docstrings.

2022-02-04 16:14 UTC, anecdata reviewed
Looks good, just a couple little typos: "unset or unset" and "then e value" in the first, and the "then e value" got pasted into the second too.

2022-02-04 16:35 UTC, jepler commented
Thanks, I fixed the docs more. I shouldn't have done it in a hurry, but I did.

2022-02-04 18:39 UTC, tannewt commented
> ```python
> from mdns import Mdns
> import wifi
> m = Mdns(radio)
> m.hostname = "qtpy"
> ```

Something like this is my preference.

Thinking ahead to support this on linux, I wonder if we want to mirror `zeroconf`: https://github.com/jstasiak/python-zeroconf/blob/master/examples/registration.py Or we mirror avahi bindings more closely. Do you want to add discovery functions too? Looks like the IDF has some available.

I want to avoid Radio becoming a catch all because I expect it to be the API for any WiFi radio.

2022-02-06 00:00 UTC, dhalbert commented
`wifi. radio` already has `.hostname`, `.mac_address`, etc. I see that stuff as an interface/protocol that other network objects would implement. So I see `radio.mdns_hostname` as another (settable) network property.

There could be a `radio.host` singleton that holds all this info, and `radio.hostname` would then be an (eventually deprecated) shortcut for `radio.host.hostname`, etc.

2022-02-13 17:48 UTC, closed without merging

2022-03-15 21:34 UTC, tannewt commented
I'm picking this up. I want to experiment with MDNS.