Add Makerfabs ESP32-S2 Parallel TFT board
adafruit/circuitpython pull request #6119
Opened 2022-03-05 18:11 UTC by deshipu

The basic settings and pins are fine, I'm still working on getting the
display to work, I will update it when I get the right init sequence.

More information:
https://www.makerfabs.com/wiki/index.php?title=ESP32-S2_Parallel_TFT_with_Touch(3.5%27%27)

2022-11-15 23:16 UTC, tannewt commented
Any update on this?

2022-11-18 04:46 UTC, MicroDev1 requested changes

2022-11-18 04:46 UTC, MicroDev1 commented on ports/espressif/boards/makerfabs_esp32s2_parallel_tft/mpconfigboard.mk
> +CFLAGS += -DCFG_TUD_TASK_QUEUE_SZ=32
```suggestion
```
These have been moved to common `mpconfigport.mk` and can be removed.

2022-11-18 05:11 UTC, MicroDev1 commented on ports/espressif/boards/makerfabs_esp32s2_parallel_tft/mpconfigboard.h
> +#define BOARD_USER_SAFE_MODE_ACTION translate("pressing boot button at start up.\n")
```suggestion
```
This message is now the default and can be removed.

2022-11-18 15:47 UTC, deshipu commented
> Any update on this?

@tannewt No updates. The display doesn't work correctly either in the 8bit or ther 16bit mode, and I couldn't get it working with the current libraries. There is some work to be done with the parallelio before this is working, but I don't currently have the cycles to work on it.

2022-11-28 21:36 UTC, dhalbert commented
We discussed closing draft issues that are stuck in the CircuitPython meeting on 2022-11-28 in In the Weeds.

Closing for now. Can be reopened. Tracking in issue #7266, which will remain open.

2022-11-28 21:36 UTC, closed without merging