Fix countio.Counter.__init__ type hints
adafruit/circuitpython pull request #6162
Opened 2022-03-16 03:59 UTC by prplz

Some fixes with `countio.Counter.__init__` typing:
- Parameter `pull` was missing its default of `None`, causing IDEs to falsely warn/error
- Docstring was missing the name of  params `edge` and `pull`.

2022-03-16 17:12 UTC, tannewt requested changes
You are accidentally changing the esp-idf here too. It was updated yesterday so you may have pulled without updating submodules.

The fix itself looks good. Thanks!

2022-03-16 20:10 UTC, prplz commented
Oops, I caught that locally but never pushed. Thanks!

2022-03-16 20:57 UTC, dhalbert approved these changes
Great, thanks!

2022-03-17 17:02 UTC, tannewt approved these changes

2022-03-17 17:02 UTC, merged