Enable support for extended HID usage page and usage. Related to Supp…
adafruit/circuitpython pull request #6239
Opened 2022-04-05 02:24 UTC by ReeceRobinson

Enable support for extended HID usage page and usage. Related to Support HID Usage Pages and Usages >255 #5529.
Also added suppression for array-bounds warning to enable mpy-cross to build on Mac.

2022-04-05 13:10 UTC, dhalbert requested changes
This looks good! I will make the one change noted and then re-run.

2022-04-05 13:10 UTC, dhalbert commented on mpy-cross/mpy-cross.mk
> +CWARN += -Wno-array-bounds
This was fixed in #6231 so we can take this back out.
```suggestion
```

2022-04-05 13:13 UTC, dhalbert commented
I fixed a minor build problem to make sure this works for all builds including espressif. Will merge when done.

2022-04-05 13:13 UTC, dhalbert approved these changes

2022-04-05 16:40 UTC, merged

2022-04-06 07:38 UTC, ReeceRobinson commented
Awesome! Thank you Dan for resolving  the issues to get this merged. Your efforts made it easy for me to contribute to this project.