Add MixGo CE board
adafruit/circuitpython pull request #6383
Opened 2022-05-11 13:00 UTC by dahanzimin

Thank circuitpython for adding a new board to circuitpython ， I hope it can pass

2022-05-11 16:58 UTC, tannewt submitted a review, later dismissed
Why are you including the library as a frozen?

2022-05-11 16:58 UTC, tannewt commented on ports/espressif/boards/mixgo_ce_udisk/mpconfigboard.mk
> +USB_PID = 0x80A8
You'll need your own USB VID/PID combination. Espressif usually gives them out here: https://github.com/espressif/usb-pids

2022-05-18 12:47 UTC, dhalbert commented
@dahanzimin Are you still awaiting the USB PID from Espressif, or is the one in the commit what you got?

2022-05-19 01:16 UTC, dahanzimin commented
@dhalbert ,Thank you for your attention. I have applied for PID in Lexin ands ubmitted them [PID](https://github.com/adafruit/circuitpython/pull/6383/commits/d4b02e22ae7fc7aa47e6ae46f9bd364e196ca57a)，I don't know what else to do next, just waiting for the merger?

> @大汉子民你还在等待来自Espressif的USB PID，还是在提交中的那个是你得到的？

2022-05-19 12:34 UTC, dhalbert requested changes
Thanks for the update on the USB PID.

Two comments about your custom library:

1) The usual way to do this is to keep the library in a separate repo, and add it as a submodule. This will allow you to maintain the library separately, and not depend on the `circuitpython` repo for source control. Also it reduces the size of `circuitpython` and minimizes the custom code in it.

2) Consider whether you need to freeze the library. The reason we freeze libraries into certain firmware images is only to save RAM space when importing the libraries. It is not purposely to make using the board more convenient, though that is an accidental effect. Circuit Playground Express (SAMD21, with only 32kB of RAM) has several frozen libraries for the RAM space reason. But Circuit Playground Bluefruit (nrf52840, 256kB RAM) has none. ESP32-S2 WROOM has 320kB RAM, so you are not under extremem RAM size pressure.

The disadvantage of freezing libraries is that updates require building new firmware. If you keep the libraries separate, then your users will not have to upgrade firmware merely to update the frozen libraries. Of course, they can always override the frozen libraries by placing new versions before `.frozen` in `sys.path`.

Given the size of your custom library, it is probably going to have bug fixes and improvements going forward.

2022-05-19 13:28 UTC, dhalbert commented
Note also the pre-commit failures here: https://github.com/adafruit/circuitpython/runs/6398538029?check_suite_focus=true. For some files, there is simply extraneous whitespace or a missing newline at the end of the file. For the Python files, they may be failing `black` or `pylint` in some way. If you move to your own repo and a submodule, they will not be checked (you could of course check them yourself).

2022-05-20 02:15 UTC, dahanzimin commented
Thank you very much for your help. We use this board to promote the programming education of circuit Python in China, and use the graphical programming software [mixly](https://mixly.org) in primary and middle school students. They often don't want complex lib operation

2022-05-20 03:05 UTC, dahanzimin commented
> Note also the pre-commit failures here: https://github.com/adafruit/circuitpython/runs/6398538029?check_suite_focus=true. For some files, there is simply extraneous whitespace or a missing newline at the end of the file. For the Python files, they may be failing `black` or `pylint` in some way. If you move to your own repo and a submodule, they will not be checked (you could of course check them yourself).

Sorry, I will pay attention to this detail later. Thank you for your answers and help

2022-05-20 03:07 UTC, dhalbert commented
Here is some info about using `pre-commit` to check the files: https://learn.adafruit.com/building-circuitpython/build-circuitpython#install-pre-commit-3096511-10

2022-05-21 15:39 UTC, dahanzimin commented
@dhalbert  Thank you for your help. Now all checks have passed. What else do I need to do for this merger?

2022-05-22 00:24 UTC, dhalbert reviewed
This looks good; thank you for making the submodule.

One question before merging: why is the `sdkconfig` empty? See the others in `boards/*/sdkconfig`. Some just specify `CONFIG_LWIP_LOCAL_HOSTNAME`; others have more settings.

2022-05-22 12:21 UTC, dhalbert commented
@dahanzimin is it ready for review again?

2022-05-22 12:42 UTC, dahanzimin commented
> @dahanzimin is it ready for review again?

OK, thank you again. As always, I will promote circuitpython in another region. The board program has been added and can be reviewed again. Thank you

2022-05-22 12:47 UTC, dhalbert approved these changes
Looks good to me! Thanks for addressing our requests. I see that https://github.com/adafruit/circuitpython-org/pull/946 for the Mixgo CE board. But are there now two boards, or are they different modes of the same board? Since there are two builds, I think you will want another entry in circuitpython.org.

2022-05-22 12:47 UTC, merged

2022-05-22 12:58 UTC, dahanzimin commented
Yes, the same board has different modes (considering that many computers cannot read the drive letter when programming), in circuit python org. Need two web pages to support it? Submit another (mixgo_ ce_ serial) page later.

2022-05-22 14:22 UTC, dhalbert commented
Yes, if there are two builds, you will need another page for the other download.

2022-05-22 14:27 UTC, dhalbert commented
@dahanzimin - the merge documentation build failed, I believe because the frozen library was in the board directory rather than in  `frozen/`. Could you submit another PR that moves the submodule to the `frozen/` directory, and change your `mpconfigboard.mk` files appropriately?

2022-05-22 14:28 UTC, dhalbert commented
Error here: https://github.com/adafruit/circuitpython/runs/6543811274?check_suite_focus=true

2022-05-22 14:40 UTC, dhalbert commented
To test this before pushing the new PR, go to the top level and do `make html`. You will need to do `pip3 install -r requirements.doc.txt` to get all the Python libraries to build the documentaiton.

2022-05-23 03:10 UTC, dhalbert commented
@dahanzimin I am fixing this in #6420.

2022-05-23 03:53 UTC, dahanzimin commented
Thank you. I'm already repairing it [dahanzimin/circuitpython/commit/](https://github.com/dahanzimin/circuitpython/commit/6454c5895b9f665d7f7ddf60155e7a6e2fe41660),[Actions](https://github.com/dahanzimin/circuitpython/actions/runs/2368760801) are in progress