Lilygo TTGO T-OI Plus ESP32C3
adafruit/circuitpython pull request #6387
Opened 2022-05-12 15:45 UTC by SimonVail

2022-05-12 15:55 UTC, Neradoc requested changes
If you accept the changes, that should make pre-commit happy.

2022-05-12 15:55 UTC, Neradoc commented on ports/espressif/boards/Lilygo-T-oi-Plus-ESP32C3/board.c
> +}
```suggestion
void board_init(void) {
}
```
Remove blank spaces/empty line.

2022-05-12 15:55 UTC, Neradoc commented on ports/espressif/boards/Lilygo-T-oi-Plus-ESP32C3/mpconfigboard.mk
> +CIRCUITPY_ESP_FLASH_SIZE = 4MB
```suggestion
CIRCUITPY_ESP_FLASH_SIZE = 4MB

```
Add newline at the end of file.

2022-05-12 15:55 UTC, Neradoc commented on ports/espressif/boards/Lilygo-T-oi-Plus-ESP32C3/pins.c
> +    { MP_ROM_QSTR(MP_QSTR_IO4), MP_ROM_PTR(&pin_GPIO4) },
```suggestion
    { MP_ROM_QSTR(MP_QSTR_IO18), MP_ROM_PTR(&pin_GPIO18) },

    { MP_ROM_QSTR(MP_QSTR_IO4), MP_ROM_PTR(&pin_GPIO4) },
```
Remove blank spaces.

2022-05-12 23:22 UTC, SimonVail commented
All Check Passed !!!!

2022-05-13 18:25 UTC, tannewt requested changes
One small change to switch to a unique creation id. I added it here: https://github.com/creationid/lilygo-creations/blob/main/README.md

2022-05-13 18:25 UTC, tannewt commented on ports/espressif/boards/lilygo_ttgo_t-oi-plus/mpconfigboard.mk
> +CIRCUITPY_CREATION_ID = 0x00C30001
```suggestion
CIRCUITPY_CREATION_ID = 0x00C30002
```

2022-05-13 22:26 UTC, dhalbert commented
I saw the LilyGo TTO T-01-C3 we already defined, and thought maybe it is a typo, but it is a board with many fewer pins. So there 1`is a Lilygo board with `OI` (oh eye) in its anme, and another board with `01` (zero one) in its name. Oy.

2022-05-13 22:31 UTC, dhalbert approved these changes
Thanks for the updates!

2022-05-13 22:31 UTC, merged