tilegrid.contains() function
adafruit/circuitpython pull request #6442
Opened 2022-05-27 23:10 UTC by FoamyGuy

This adds a `tilegrid.contains()` function that accepts a touch tuple from adafruit_touchscreen library (or similar) and returns true or false based on whether the touch point is inside the rectangular bounds of this tilegrid.

2022-05-31 21:09 UTC, tannewt requested changes
Two minor nitpicks. Thanks for adding this! Group would be cool to do too.

2022-05-31 21:09 UTC, tannewt commented on shared-module/displayio/TileGrid.c
> +    }
Nitpick. They baked "boolean zen" into us at uni.
```suggestion
    return x >= self->x && x <= right_edge &&
        y >= self->y && y <= bottom_edge;
```

2022-06-03 22:00 UTC, tannewt commented on shared-module/displayio/TileGrid.c
> +        y >= self->y && y <= bottom_edge;
To make the formatter happy.
```suggestion
    return x >= self->x && x <= right_edge &&
           y >= self->y && y <= bottom_edge;
```

2022-06-03 22:06 UTC, FoamyGuy commented
Thank you! latest commits make those changes. I retested it successfully on PyPortal Titano with this code:
```
import board
import displayio
import adafruit_touchscreen

display = board.DISPLAY

ts = adafruit_touchscreen.Touchscreen(
    board.TOUCH_XL,
    board.TOUCH_XR,
    board.TOUCH_YD,
    board.TOUCH_YU,
    calibration=((5200, 59000), (5800, 57000)),
    size=(display.width, display.height),
)

# Setup the file as the bitmap data source
bitmap = displayio.OnDiskBitmap("/purple.bmp")

# Create a TileGrid to hold the bitmap
tile_grid = displayio.TileGrid(bitmap, pixel_shader=bitmap.pixel_shader)

tile_grid.x = 50
tile_grid.y = 50

# Create a Group to hold the TileGrid
group = displayio.Group()

# Add the TileGrid to the Group
group.append(tile_grid)

# Add the Group to the Display
display.show(group)

# Loop forever so you can enjoy your image
while True:
    p = ts.touch_point
    if p:
        print(p)
        if tile_grid.contains(p):
            print("Touching Flowers")
        else:
            print("Outside")

```

2022-06-03 22:13 UTC, tannewt approved these changes
Thank you!

2022-06-03 22:52 UTC, FoamyGuy commented
One more commit to fix an off by 1 error. Turns out the right and bottom edges were returning True for one pixel too large.

2022-06-06 18:02 UTC, tannewt approved these changes
Looks good! Thank you!

2022-06-06 18:02 UTC, merged