palette_index validation in Palette functions
adafruit/circuitpython pull request #6515
Opened 2022-06-22 03:20 UTC by FoamyGuy

This adds bounds validation for the `palette_index` argument for `make_transparent()`, `make_opaque()` and `is_transparent()` functions on the Palette object.

Resolves: #6507

2022-06-22 16:44 UTC, tannewt requested changes
Thanks for adding these checks! Mind using [mp_arg_validate_int_range](https://github.com/adafruit/circuitpython/blob/main/py/argcheck.c#L180=) instead? That way you won't introduce another string to be translated.

2022-06-23 02:34 UTC, FoamyGuy commented
I'm not sure how to pass the name as the last argument `arg_name`

I tried like this:

```
palette_index = mp_arg_validate_int_range(palette_index, 0, common_hal_displayio_palette_get_len(self)-1, "palette_index");
```

But I get build error this way. I found some usages of that function what pass names like e.g. `MP_QSTR_usage` but I'm not sure in the case of `"palette_index"` how to get this qstr object.

2022-06-23 12:19 UTC, FoamyGuy commented
Ah, it seems these `MP_QSTR_` things can exist without being explicitly created previously. 

Most instances I found using `mp_arg_validate_int_range()` were in constructor methods with arguments that were defined with MP_QSTR things. I did find one in TileGrid that seemed to be using an otherwise undeclared one `MP_QSTR_tile` and figured it was worth trying `MP_QSTR_palette_index` here to see if that would work and it did.

Ended up with this:
```
palette_index = mp_arg_validate_int_range(palette_index, 0, common_hal_displayio_palette_get_len(self)-1, MP_QSTR_palette_index);
```

2022-06-23 13:20 UTC, jepler approved these changes
I only reviewed the last commit.  Thanks!

2022-06-23 14:49 UTC, jepler approved these changes
[whoops, I intended to approve]

2022-06-23 14:49 UTC, merged