Add some frozen libraries to elecfreaks_picoed
adafruit/circuitpython pull request #6526
Opened 2022-06-28 14:38 UTC by xuhow

Hi, I know that the frozen library feature is designed for master boards in small memories. But we find it could be very convenient for users if we can distribute some common libraries with the firmware. Since our master board is designed for non-professionals(young students), we really need this and hope you can merge our pull request. Thanks.

2022-06-28 22:50 UTC, tannewt requested changes
I'm ok with these changes but the build didn't complete: https://github.com/adafruit/circuitpython/runs/7095095970?check_suite_focus=true#step%3A9%3A11= Do you have version tags in your libraries?

2022-06-29 02:38 UTC, xuhow commented
> 

My libraries have version tags and I build successfully locally. 
The git commit(28eb0526cc7c80c65f711c8b43ee83e191b5984d) that the build logging shows is from [adafruit/Adafruit_CircuitPython_IS31FL3731](https://github.com/adafruit/Adafruit_CircuitPython_IS31FL3731.git). I found the latest commit for [adafruit/Adafruit_CircuitPython_IS31FL3731](https://github.com/adafruit/Adafruit_CircuitPython_IS31FL3731.git) has no version tag, was this the reason why I failed? 
If yes, would you mind providing any tips for me? Thanks in advance.

2022-06-29 18:00 UTC, tannewt commented
Ah! You'll want to move to the is31 directory and check out the last release and then move back to the CP root and commit it. You can also run `make update-frozen-libraries` from the root. It may update others though too.

2022-06-30 03:34 UTC, xuhow commented
@tannewt thank you! it looks good now!

2022-06-30 18:53 UTC, tannewt approved these changes
Yup! Looks good! Thanks for fixing it quickly!

2022-06-30 18:53 UTC, merged