Add wifi.radio.tx_power
adafruit/circuitpython pull request #6542
Opened 2022-06-30 22:34 UTC by todbot

Addresses feature request https://github.com/adafruit/circuitpython/issues/6540

2022-06-30 22:41 UTC, jepler commented
@todbot I revised the initial comment on this PR using the [special syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) for closing an issue when a PR is accepted.

2022-06-30 23:34 UTC, askpatrickw commented
I actually started to work on this myself, and the get, set in Radio.c made sense. I also thought tx_power would need to go in `ports/espressif/common-hal/wifi/Radio.h`, is that not the case? 

I had no idea shared-bindings would need updated, so I'm glad you took this on, ty!

2022-07-01 00:44 UTC, askpatrickw commented
You didn't step on me... I don't know C so it would have been a steep learning curve.
I'll test this later tonight or tomorrow during the Deep Dive window.

Thank you again!

2022-07-01 14:46 UTC, dhalbert requested changes
Thanks! One doc clarification requested.

2022-07-01 14:46 UTC, dhalbert commented on shared-bindings/wifi/Radio.c
> +//|     """Set TX WiFi power."""
```suggestion
//|     """Wifi transmission power, in dBm."""
```

2022-07-01 17:13 UTC, tannewt commented
> I was also confused by no function decls in `ports/espressif/common-hal/wifi/Radio.h`. I think the rationale is that `shared-bindings` contains the C API headers and the individual ports' headers contain only platform-specific stuff. So, the `Radio.h` in `shared-bindings` is the header for _every_ implementation of `wifi.radio`.

This is exactly right. Another way to think about it is that the shared-bindings header declares all of the functions used by the shared-bindings implementation.

2022-07-01 17:18 UTC, dhalbert approved these changes
Thanks! Ready to merge when build is done.

2022-07-01 18:09 UTC, merged