Check parameters of int.from_bytes
adafruit/circuitpython pull request #6562
Opened 2022-07-06 05:53 UTC by isacben

Hi,

I am opening this PR to solve #6419. This is what I am trying to do:

1. Allow the method to still receive 3 parameters, since signed parameter support still needs to be implemented.
2. Add support to accept the signed keyword parameter; I did not implement signed parameter support though, but added a `NotImplementedError` if `signed=True` is passed.
3. Added a validation for the `byteorder` parameter. Not sure if this is was necessary. I added `MP_QSTR_big` here, but I am not sure how to the `qstrdefs.enum.h` file.

Please let me know if you have any feedback so I can review.

Thank you!

2022-07-06 13:13 UTC, dhalbert requested changes
Thanks for the fix! I have made some suggestions (which are not tested!).

> Added a validation for the byteorder parameter. Not sure if this is was necessary. I added MP_QSTR_big here, but I am not sure how to the qstrdefs.enum.h file.

The qstr will get added automatically; you don't need to do anything. The sources are scanned to generate the qstr's when a build is done. Make sure to do `make clean` if you change or add any qstr's, though.

I don't know whether you changed `circuitpython.pot` by hand or not. You don't need to. Just run `make translate` before committing, and it will be updated automatically.

2022-07-06 13:13 UTC, dhalbert commented on py/objint.c
> +        mp_raise_ValueError(MP_ERROR_TEXT("byteorder must be 'little' or 'big'"));
This will just say `Invalid byteorder`, which is good enough.
```suggestion
        mp_arg_error_invalid(MP_QSTR_byteorder);
```

2022-07-06 13:13 UTC, dhalbert commented on py/objint.c
> +    } else if (pos_args[2] != MP_OBJ_NEW_QSTR(MP_QSTR_big)) {
```suggestion
    } else if (args[ARG_byteorder] != MP_OBJ_NEW_QSTR(MP_QSTR_big)) {
```

2022-07-06 13:13 UTC, dhalbert commented on py/objint.c
> +            return mp_obj_int_from_bytes_impl(pos_args[2] != MP_OBJ_NEW_QSTR(MP_QSTR_little), bufinfo.len, bufinfo.buf);
```suggestion
            return mp_obj_int_from_bytes_impl(args[ARG_byteorder] != MP_OBJ_NEW_QSTR(MP_QSTR_little), bufinfo.len, bufinfo.buf);
```

2022-07-06 13:13 UTC, dhalbert commented on py/objint.c
> +    enum { ARG_signed };
```suggestion
    enum { ARG_bytes, ARG_byteorder, ARG_signed };
```

2022-07-06 14:43 UTC, dhalbert commented
@isacben I just want to know if you retested.

2022-07-06 14:56 UTC, isacben commented
Hi @dhalbert ,

Thank you very much for the helpful feedback!!

Yes, I am testing with the Feather RP2040. This is the only one I have, unfortunately!

- I wend ahead and made the changes (also tested with Feather RP2040).
- Regarding the `circuitpython.pot`, I did not updated manually; the pre-commit did it. This time I did run make translate.
- I also realized about the MO Express. I built CP for that board locally and it worked; so, I would like to see how it behaves with this changes in the CI environment.
- This second commit failed. I think it was because of this line:

```
{ MP_QSTR_bytes, MP_ARG_REQUIRED | MP_ARG_OBJ },
{ MP_QSTR_byteorder, MP_ARG_REQUIRED | MP_ARG_OBJ },
```

I think this would fix it:

```
{ MP_QSTR_bytes, MP_ARG_REQUIRED | MP_ARG_OBJ, {.u_obj = MP_OBJ_NULL} },
{ MP_QSTR_byteorder, MP_ARG_REQUIRED | MP_ARG_OBJ, {.u_obj = MP_OBJ_NULL} },
```

Please let me know what you think.

Thank you in advance!!

2022-07-06 17:02 UTC, dhalbert commented
> * This second commit failed. I think it was because of this line:
> 
> ```
> { MP_QSTR_bytes, MP_ARG_REQUIRED | MP_ARG_OBJ },
> { MP_QSTR_byteorder, MP_ARG_REQUIRED | MP_ARG_OBJ },
> ```
> 
> I think this would fix it:
> 
> ```
> { MP_QSTR_bytes, MP_ARG_REQUIRED | MP_ARG_OBJ, {.u_obj = MP_OBJ_NULL} },
> { MP_QSTR_byteorder, MP_ARG_REQUIRED | MP_ARG_OBJ, {.u_obj = MP_OBJ_NULL} },
> ```

This is only because the `unix` port has set `-Wextra`. A cheaper way would be:
```c
        { MP_QSTR_bytes, MP_ARG_REQUIRED | MP_ARG_OBJ ,{0} },
        { MP_QSTR_byteorder, MP_ARG_REQUIRED | MP_ARG_OBJ ,{0} },
```
or those lines

2022-07-06 20:32 UTC, isacben commented
Thanks Dan! I will take your advice on the initialization.

It seems now the build is too big for the Metro MO Express and the Nano 33 IoT. Please let me know if there is any recommendation on this regard. Probably I went too far with the idea of adding the signed parameter and the byteorder validation!

Thank you!

2022-07-08 02:57 UTC, dhalbert commented
@isacben I will not be able to work on this for about a week or so, but will get back to you about shrinking those builds. Thanks for working on this.

2022-07-19 23:15 UTC, dhalbert approved these changes
I made some changes to make things fit, and updated some infrastructure things.

@jepler @tannewt I made the unix port use `-std=gnu11` instead of `gnu99`. We don't need to support really old compilers. Also made a change to not include the `ru` font on SAMD21 builds, and built Feather ESP32-S3 TFT with `-Os` instead of `-O2`, rather than starting to disable more modules to make it fit.

2022-07-19 23:15 UTC, merged

2022-07-20 15:48 UTC, isacben commented
Hi @dhalbert,

Thank you very much for your help! I will have a look to the changes you made to learn about ways to shrink the builds!

Thank you!