Check uniqueness of creatorid:creationid
adafruit/circuitpython pull request #6831
Opened 2022-08-28 02:33 UTC by jepler

Turns out we already have one duplicate, so I 'endorsed' it, but probably
one should be reassigned.

Before I did so it printed a new (and slightly misleading, since it says VID/PID) message:
```
Duplicate VID/PID usage found!
- VID/PID: 0x70010001:0x00100001
  Boards: ai_thinker_esp32-c3s, ai_thinker_esp32-c3s-2m
```
so it's working.

Closes: #8628

2022-08-28 15:04 UTC, dhalbert approved these changes
Approving, but not merging: if we have a duplicate, I think it would be better to fix that now, when the whole thing is still really early, rather than live with it.

2022-08-28 15:53 UTC, jepler commented
Agreed

2022-08-28 18:15 UTC, dhalbert requested changes
> Agreed

I will change my review to Request Changes to remind us.

2022-08-28 21:45 UTC, jepler commented
I've pinged the board's creator for an allocation.

2022-08-28 23:02 UTC, dhalbert commented
Ah, I thought we had assigned it.

2022-08-29 00:08 UTC, jepler commented
It looks like the structure is that some creators have their creationids within the "creationid" organization but others like skieast don't. I'm not sure why, or which is preferred in the long run.

2022-08-29 01:08 UTC, skieast commented
> It looks like the structure is that some creators have their creationids within the "creationid" organization but others like skieast don't. I'm not sure why, or which is preferred in the long run.

I really don't know why I did it that way. Probably at the time there were no other creationids allocated so i did it 'a' way.  I can change this to whatever is currently the accepted method.

2022-08-29 02:33 UTC, jepler commented
skieast isn't the creator of either of these boards (it's "ai-thinker technology") though the allocation for the first board went via their creatorid.

should the new allocation go in espressif, since that's who the microcontroller is from? or should a new creatorid be allocated for ai-thinker?

if the answer's not clear cut I may suggest that we merge this as is (approving the current conflict) and just open a fresh new PR to get the conflict fixed. But that depends on the "cost" of changing a board's supposedly unique ID down the line, vs having more duplicates accidentally enter circuitpython because this script is not present yet.

2022-08-29 02:53 UTC, dhalbert commented
> should the new allocation go in espressif, since that's who the microcontroller is from? or should a new creatorid be allocated for ai-thinker?

I think it should go in https://github.com/creationid/creators under the manufacturer, making a new creator ID if necessary. I don't think https://github.com/skieast/creations/ is the right place.

Note that there were multiple manufacturer repos in https://github.com/creationid, but then @tannewt archived them, and put everything in one repo.

It's OK to merge this now, I just would like the conflict to be fixed at some point, with boards being given unique ID's. I thought it would be easy to do in the same PR, but making another one is fine.

2022-08-29 16:56 UTC, askpatrickw commented
If you need help with the Creator stuff, feel free to ping me. Tannewt and I evolved that process into the single repo approach you see now.

2022-08-29 18:14 UTC, jepler commented
@dhalbert can you switch the review back to approved so we can merge this and at least make sure we don't have any new duplicates going forward? the duplicate we can track in #6839.

2022-08-29 19:01 UTC, dhalbert approved these changes

2022-08-29 19:01 UTC, merged