Support for opening a file by name in MP3Decoder
adafruit/circuitpython pull request #6943
Opened 2022-09-23 17:29 UTC by snkYmkrct

Hi @jepler  ! 🐈‍⬛ 🐈‍⬛ 

Based on our discussion in #6931, I added a method that takes a mp3 file name as input, opens the mp3 file, and replaces the old opened file in the current MP3Decoder object. 

Please let me know if this is what you had in mind, and it looks good. 

Thank you!

2022-09-24 22:20 UTC, jepler commented on shared-bindings/audiomp3/MP3Decoder.c
> +    { MP_ROM_QSTR(MP_QSTR_open_file), MP_ROM_PTR(&audiomp3_mp3file_open_file_obj) },
I thought maybe this would be `mp3file.open`, `open_file` feels a bit like a redundant name.

2022-09-24 22:22 UTC, jepler requested changes
Thanks! I have some feedback. I also didn't do any testing. If you did test, it would be helpful to say what you tested.

2022-09-24 22:22 UTC, jepler commented on shared-bindings/audiomp3/MP3Decoder.c
> +    }
can skip this check.  Passing the wrong type will be detected inside `mp_builtin_open_obj`, with a message like `TypeError: can't convert 'list' object to str implicitly`.

2022-09-24 22:22 UTC, jepler commented on shared-bindings/audiomp3/MP3Decoder.c
> +    }
Can skip this check, it's guaranteed that the file was just opened in byte mode by the arguments to `mp_builtin_open_obj`.

2022-09-24 22:56 UTC, snkYmkrct commented
Thank your for the feedback, I am learning the project structure and macros, so this is very helpful. 
I will make the changes you requested. 

I forgot to mention in the original text, but yes, I did test the code, on the Pyportal Titano, and PyGamer. 
Seems to be working correctly, replacing the file in the MP3Decoder object, and play file works as expected.

2022-09-25 10:32 UTC, snkYmkrct commented
@jepler 
I made the requested changes. 
There is one failed check, I don't know what that error means.

2022-09-25 11:48 UTC, jepler approved these changes
Thanks!

2022-09-25 21:53 UTC, dhalbert commented
The failure is an unrelated doc build problem, so I'll merge anyway.

2022-09-25 21:53 UTC, merged

2022-09-25 22:13 UTC, snkYmkrct commented
Thank you!