Ensure orderly shutdown of ssl socket
adafruit/circuitpython pull request #7291
Opened 2022-12-02 01:40 UTC by jepler

A crash would occur if an SSL socket was not shut down before `gc_deinit()`.

I do not fully understand the root cause, but some object deinitialization / deallocation prior to `gc_deinit` leaves the SSL object in an inconsistent state.

Rather than resolve the root cause, instead ensure that the closing of the user socket also closes the SSL socket.

Testing performed: on Feather ESP32S3 TFT run the reproducer script >10 times. Before, it crashed after 1 time. However, running 10 times helps show I'm not using up socket file descriptors accidentally.

This feels a bit voodoo so I'd love it if instead of incorporating this blindly, someone else went deeper and found the truth.

Closes: #6502

2022-12-02 16:44 UTC, dhalbert commented
I am going to spend a little time seeing if I can find the root cause.

2022-12-02 18:04 UTC, dhalbert commented
I do not understand the flow all that well, but this seems a bit fishy to me:
https://github.com/adafruit/circuitpython/blob/9e104c04aec3178b45ba70a302ad5800afad752f/ports/espressif/common-hal/socketpool/Socket.c#L609-L616
Under what circumstances is the passed in `socket` _not_ a `Socket` object. Could it be an `SSLSocket`? If so then fields in it are set willy-nilly. Also the SSLSocket is not shut down. And if it's a plain `Socket`, it's kind of being rendered unfunctional, but the underlying lwip socket isn't decommissioned in any way.

2022-12-02 18:05 UTC, dhalbert requested changes
One idea, and also a question in the main comments thread.

2022-12-07 21:50 UTC, jepler commented
I had a theory that for an ssl socket `sss` created from a regular socket `s`, closing `s` first then `sss` could provoke the same problem without going through interpreter shutdown. However, I was not able to make this happen in practice.

2022-12-07 21:54 UTC, jepler commented
The program I tried:
```
import wifi, socketpool, ssl, time, gc
wifi.radio.connect('<omitted>')
import socketpool
socket = socketpool.SocketPool(wifi.radio)
ctx = ssl.create_default_context()

b = bytearray(24)
for i in range(8):
    print(i)
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sss = ctx.wrap_socket(s)
    sss.connect(('finance.yahoo.com', 443))
    print(sss.send(b"GET /quote/%5EIXIC HTTP/1.0\r\nHost: finance.yahoo.com\r\n\r\n"))
    print(sss.recv_into(b))
    print(bytes(b))
    s.close()
    gc.collect()
    sss.close()
    gc.collect()
```

2022-12-07 23:56 UTC, jepler commented
> Under what circumstances is the passed in `socket` _not_ a `Socket` object? Could it be an `SSLSocket`? If so then fields in it are set willy-nilly. Also the `SSLSocket` would not be shut down. And if it's a plain `Socket`, it's kind of being rendered unfunctional, but the underlying lwip socket isn't decommissioned in any way.

Scott answered this in a voice chat. The routine is actually _initializing_ a socket object for use by the web workflow. The name is not very self-documenting, so changing it and adding appropriate comments would be welcome as a separate PR.

2022-12-07 23:57 UTC, jepler commented on ports/espressif/common-hal/socketpool/Socket.h
> +    struct ssl_sslsocket_obj *ssl_socket;
Done

2022-12-08 00:12 UTC, dhalbert approved these changes
:+1:

2022-12-08 00:12 UTC, merged