mimxrt10xx: implement i2sout
adafruit/circuitpython pull request #7764
Opened 2023-03-21 17:04 UTC by jepler

mimxrt10xx: implement i2sout

tested on metro m7 (green prototype version) with max98357a i2s amplifier and the following test code:
```py
import board
import time
import digitalio
from audiobusio import I2SOut
from audiocore import RawSample
from microcontroller import pin
from ulab import numpy as np

n = np.array(np.sin(np.linspace(0, np.pi*2, 218, endpoint=False)) * 200, dtype=np.int16)
print(n)
r = RawSample(n, sample_rate=8000, channel_count=2)
def main():
    with digitalio.DigitalInOut(board.LED) as l:
        l.switch_to_output(True)
        value = False
        while True:
            with I2SOut(pin.GPIO_06, pin.GPIO_07, pin.GPIO_04) as i:
                time.sleep(.01)
                l.value = value = not value
                i.play(r, loop=True)
                print(i.playing)
                time.sleep(.5)
                i.stop()
                print("STOPPED")
                print(i.playing)
                time.sleep(.5)
                i.play(r, loop=True)
                print(i.playing)
                print("PLAY AGAIN")
                time.sleep(.5)
            time.sleep(1)
```

Only stereo, 16-bit, raw samples were tested; the sample rate is actually fixed
at 48kHz in the core right now. There is more to do, but this basic test works.

2023-03-21 19:51 UTC, jepler commented
it needs the tables of i2s pins written for the other micros

2023-03-22 16:55 UTC, tannewt requested changes
Two questions. Looks good otherwise!

2023-03-22 16:55 UTC, tannewt commented on ports/mimxrt10xx/common-hal/audiobusio/__init__.c
> +        memset(ptr, 0, (end - ptr) * sizeof(uint32_t));
Don't we allow the user to set the quiescent value? Or is it ok that it is always signed?

2023-03-22 18:27 UTC, jepler commented on ports/mimxrt10xx/background.c
>      #endif
Done

2023-03-23 17:07 UTC, tannewt approved these changes
Thank you!

2023-03-23 17:07 UTC, merged