raise kernel load addr and slip stack under kernel on both 32bit and 64bit
adafruit/circuitpython pull request #8305
Opened 2023-08-21 20:54 UTC by cleverca22

while using circuitpython on a pi-zero, i discovered that the stack code code was broken
32bit was operating in dynamic stack mode, but reporting entirely wrong addresses for things
but i noticed, aarch64 on the broadcom port, puts the stack below the kernel load addr

so i just used `kernel_address=0x100000` to change the load addr, for both 32bit and 64bit, raising it up a bit more
and made both 32bit and 64bit both have the stack below the kernel, allowing for the code to be simpler

2023-08-24 04:08 UTC, RetiredWizard commented
I've tested this on both a Zero W and a Zero 2W and it looks like it fixes #8044 for the Zero. The Zero 2W still has issues with USB activity causing hangs but if you use a terminal over the RX/TX pins, the Zero 2W has been relatively stable. During my testing I didn't see any negative impact from this PR on either Zero or the Zero 2W.

2023-08-24 18:40 UTC, tannewt requested changes
I think you've updated the broadcom-peripherals library on your fork. Please PR those changes to the adafruit version first and then point this PR to it. (Sorry it is annoying.) IIRC tinyusb also uses the peripheral library for its testing.

2023-08-25 16:44 UTC, tannewt commented
I think you want to point to https://github.com/adafruit/broadcom-peripherals/commit/ec1043800fc987f7067fc07615193439843695d6 since it is derived from the merge commit. (That repo is a little weird.)

2023-08-25 18:51 UTC, cleverca22 commented
that might explain why i had an extra 40 commits in my original pr

2023-08-28 19:52 UTC, tannewt approved these changes
Thanks for the fix!

2023-08-28 19:52 UTC, merged