New UM boards setup for 9.x
adafruit/circuitpython pull request #8502
Opened 2023-10-22 07:34 UTC by UnexpectedMaker

Updated files for new Unexpected Maker boards to make them conform with new sdkconfig setup

2023-10-23 21:25 UTC, tannewt requested changes
Please try `qio` for quad io to the flash. In `dio` was only used for flashing. Now it controls the speed it actually executes at. qio flashing gets automatically downgraded to dio now.

2023-10-23 21:25 UTC, tannewt commented on ports/espressif/boards/unexpectedmaker_bling/mpconfigboard.mk
> +CIRCUITPY_ESP_FLASH_MODE = dio
You probably want this to be qio. This will run the flash in dual mode.

2023-10-23 21:25 UTC, tannewt commented on ports/espressif/boards/unexpectedmaker_blizzard_s3/mpconfigboard.mk
> +CIRCUITPY_ESP_FLASH_MODE = dio
This too.

2023-10-23 21:25 UTC, tannewt commented on ports/espressif/boards/unexpectedmaker_tinywatch_s3/mpconfigboard.mk
> +CIRCUITPY_ESP_FLASH_MODE = dio
This also

2023-10-27 08:09 UTC, UnexpectedMaker commented
Hey @tannewt - Sorry for the delay in replying, been busy making hardware all week. Sure, I'll change this and get the PR updated.

2023-10-30 17:20 UTC, tannewt reviewed
Looks good but it looks like you'll need to merge main into this. (Maybe the 8.2.x versions of these boards were merged in with 8.2.7)

2023-11-11 02:00 UTC, dhalbert commented
Closing this as superseded by #8575, but no problem with a new PR that adjusts things slightly as needed.

2023-11-15 17:02 UTC, closed without merging