merge 8.2.x to main
adafruit/circuitpython pull request #8575
Opened 2023-11-10 01:01 UTC by dhalbert

@UnexpectedMaker could you look over the revised files for your boards? Thanks.

2023-11-10 23:00 UTC, tannewt requested changes
I think you want the flash to be `qio` as well.

2023-11-10 23:09 UTC, dhalbert commented on ports/espressif/boards/unexpectedmaker_bling/mpconfigboard.mk
> +CIRCUITPY_ESP_FLASH_MODE = dio
confirmed by @UnexpectedMaker

2023-11-10 23:09 UTC, dhalbert commented on ports/espressif/boards/unexpectedmaker_tinywatch_s3/mpconfigboard.mk
> +CIRCUITPY_ESP_FLASH_MODE = dio
confirmed by @UnexpectedMaker

2023-11-10 23:18 UTC, tannewt approved these changes
Thank you!

2023-11-11 01:42 UTC, merged

2023-11-11 01:51 UTC, UnexpectedMaker commented
Thanks @dhalbert !