Add new board: Cytron Maker UNO RP2040
adafruit/circuitpython pull request #8649
Opened 2023-11-22 07:03 UTC by noqman

Hi,

Can you please help to add this new board : Cytron Maker UNO RP2040 ?

Thanks

2023-11-23 02:53 UTC, dhalbert requested changes
Hi - one typo, and pre-commit says there are blank lines with trailing spaces in `pins.c`. See https://learn.adafruit.com/building-circuitpython/build-circuitpython#install-pre-commit-3096511 for more information about using pre-commit locally to catch these kinds of things.

You can also set some editors to automatically remove trailing spaces and trailing blank lines.

2023-11-23 02:53 UTC, dhalbert commented on ports/raspberrypi/boards/cytron_maker_uno_rp2040/pins.c
> +    { MP_ROM_QSTR(MP_QSTR_LED21), MP_ROM_PTR(&pin_GPI21) },
Typo
```suggestion
    { MP_ROM_QSTR(MP_QSTR_LED21), MP_ROM_PTR(&pin_GPIO21) },
```

2023-11-28 16:04 UTC, dhalbert commented
Hi @noqman -
There are still two problems with the formatting. See https://github.com/adafruit/circuitpython/actions/runs/6967019048/job/18958156375?pr=8649
1. `mpconfigboard.mk` needs a single newline at the end.
2. There are lines that consist solely of spaces in `pins.c`.

I would fix these for you but you have not given permission for maintainers to push to your PR branch.

2023-11-29 04:33 UTC, dhalbert commented
I'm not sure what happened. Your commit f2b39ae contained some extraneous changes unrelated to to your new board. Merging from upstream did not fix that. If you `git reset --hard` back to 6d02f12 and then just fix `mpconfigboard.mk` and `pins.c` and `git push -f`, I think it will be OK.

2023-11-30 04:46 UTC, noqman commented
Hi, I have implemented all your suggestions. Please let me know if any further revisions or changes are needed. 

Thank you and I truly appreciate your guidance.

2023-11-30 14:19 UTC, dhalbert approved these changes
OK, this looks fine. Thanks for your patience with the formatting changes!

2023-11-30 14:20 UTC, merged