M5 stamp s3 cardputer build
adafruit/circuitpython pull request #8810
Opened 2024-01-18 17:32 UTC by jamesjnadeau

This is my working build of circuit python for the M5 stack cardputer.

I have updated the USB parameters per https://github.com/espressif/usb-pids

Thanks for your time and for making this pretty easy to get going, your docs are fabulous!

2024-01-18 17:33 UTC, jamesjnadeau commented
not sure what was up with the .pot file change... I can remake without that...

2024-01-18 17:51 UTC, tannewt requested changes
Yes, please remove the .pot file too. It will be autoupdated separately. Thanks for the new board def!

2024-01-18 17:51 UTC, tannewt commented on ports/espressif/boards/m5stack_cardputer/mpconfigboard.mk
> +USB_MANUFACTURER = "M5STACK"
These look like the values for a different board. Please update.

2024-01-20 12:16 UTC, jamesjnadeau commented
I'm going to close this and resubmit

2024-01-20 12:16 UTC, closed without merging