remove common_hal_pwmio_pwmout_never_reset and remaining pwmout_reset
adafruit/circuitpython pull request #8991
Opened 2024-02-29 15:34 UTC by dhalbert

Finishes remaining needed removals from #8966 and https://github.com/adafruit/circuitpython/pull/8990#issuecomment-1970468546, and some other unused code.

2024-02-29 18:22 UTC, tannewt requested changes
Sorry for misleading you on this. I think we do need the indirect pin never_reset calls. We can remove these once the blanket pin reset is removed too.

2024-02-29 18:22 UTC, tannewt commented on ports/atmel-samd/common-hal/pwmio/PWMOut.c
> -    never_reset_pin_number(self->pin->number);
This is why we still need this. Or at least, we need to replace the pwm never_reset with pin never_reset.

2024-02-29 18:24 UTC, dhalbert commented
Since this is innocuous, and we probably don't want to do the pin never-reset removal for 9.0.0, I can make this a draft and mark it 9.x.x.

2024-07-02 20:16 UTC, dhalbert commented
Closing in favor of issue #8960.

2024-07-02 20:17 UTC, closed without merging