Switch cyw43-driver to georgerobotics/cyw43-driver tag v1.0.3.
adafruit/circuitpython pull request #9016
Opened 2024-03-07 03:32 UTC by eightycc

Switch submodule cyw43-driver back to upstream repository at tag v1.0.3.

The additional pulls in our local fork have been merged into the upstream repository. The pulls are: https://github.com/georgerobotics/cyw43-driver/pull/107 and https://github.com/georgerobotics/cyw43-driver/pull/108.

2024-03-07 04:06 UTC, eightycc commented
Requesting review. Single CI failure looks like the timing related `silabs` bug we've seen before.

2024-03-07 17:56 UTC, tannewt requested changes
Just in case branches are case sensitive.

2024-03-07 17:56 UTC, tannewt commented on .gitmodules
> +	branch = MAIN
```suggestion
	branch = main
```

2024-03-07 22:04 UTC, eightycc commented
It's fine with me to hold this for 9.0.x. There are only a couple of PRs that went into v1.0.3 that weren't already on Adafruit fork we are currently using, none of them affecting CP. I've manually inspected them, and don't see any issues. In the meantime, I'll switch my work to v1.0.3 and continue testing with it.

2024-03-08 00:54 UTC, closed without merging

2024-03-08 16:23 UTC, eightycc commented
Cleaning up, didn't realize it would kill the PR. Will resubmit.

On Fri, Mar 8, 2024 at 7:41 AM Dan Halbert ***@***.***> wrote:

> @eightycc <https://github.com/eightycc> Did you close this deliberately,
> or were you just reconstituting your fork?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/circuitpython/pull/9016#issuecomment-1985916937>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB5CXR3DFWANJ6HZBZLE23DYXHLZNAVCNFSM6AAAAABEKHABY2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOBVHEYTMOJTG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>