Paulskpt lolin s3 pro
adafruit/circuitpython pull request #9030
Opened 2024-03-10 14:40 UTC by PaulskPt

To add a new board, Lolin S3 PRO, yet not existing in circuitpython.org/downloads. @tannewt advised me to add this board and to create a PR.

2024-03-11 17:14 UTC, tannewt requested changes
Thank you for the PR. There is one extra file.

2024-03-11 17:14 UTC, tannewt commented on ports/silabs/gecko_sdk
This file shouldn't be changed for adding an ESP board def.

2024-03-11 19:10 UTC, PaulskPt commented on ports/silabs/gecko_sdk
I did not change this file. It appeared in my fork & branch. I performed a clean clone. How do I proceed?

2024-03-12 17:04 UTC, tannewt commented on ports/silabs/gecko_sdk
This can happen if the submodule wasn't updated correctly and then it was accidentally "added" to a commit. The easiest way to avoid it is to ensure you only add what you want to a commit. I'll follow up with a fix.

2024-03-12 17:31 UTC, tannewt commented on ports/silabs/gecko_sdk
I pushed a commit to fix it to your branch.

2024-03-13 21:20 UTC, tannewt approved these changes
Thank you!

2024-03-13 21:20 UTC, merged