shared-module/fourwire/FourWire.c: make the chip_select pin optional
adafruit/circuitpython pull request #9106
Opened 2024-03-28 08:20 UTC by Fabien-Chouteau

If there's only one device on the bus, the chip_select pin of the peripheral can be fixed in hardware, therefore lowering the number of pins required on the microcontroller side.

This patch allows this by making the chip_select pin optional.

2024-03-28 13:46 UTC, dhalbert requested changes
This doesn't look finished. There are a number of places in `shared-module/fourwire/FourWire.c` where `self.chip_select` is referenced and assumed not to be `None`, e.g. line 83, and a bunch of others.

2024-03-30 10:10 UTC, Fabien-Chouteau commented
I'm sorry @dhalbert, I am not familiar with the codebase and I should've spend more time on this.

I added checks for the chip_select pin.

2024-04-03 00:14 UTC, dhalbert requested changes
Thanks for the update. One more place to test if chip_select pin is set or not:
```c
void common_hal_fourwire_fourwire_deinit(fourwire_fourwire_obj_t *self) {
    if (self->bus == &self->inline_bus) {
        common_hal_busio_spi_deinit(self->bus);
    }

    common_hal_reset_pin(self->command.pin);
    common_hal_reset_pin(self->chip_select.pin);     //// *************
    common_hal_reset_pin(self->reset.pin);
}
```

2024-04-03 06:41 UTC, Fabien-Chouteau commented
Hi @dhalbert 

> Thanks for the update. One more place to test if chip_select pin is set or not:

Since the `command` pin can also be None and is not checked here, my understanding is that the `common_hal_reset_pin` will check if the pin is None:
```c
void common_hal_reset_pin(const mcu_pin_obj_t *pin) {
    if (pin == NULL) {
        return;
    }
    reset_pin_number(pin->port, pin->number);
}
```

But maybe there is an oversight on the `command` pin as well.

2024-04-05 02:37 UTC, dhalbert commented
> Since the `command` pin can also be None and is not checked here, my understanding is that the `common_hal_reset_pin` will check if the pin is None:

This depends on `self->chip_select` being initialized to zero, so `self->chip_select.pin` will be `NULL` (zero) at first. I was worried about that at first, but I cannot think of a situation where the pin might be set to a non-NULL value and then later the chip_select type was set to NoneType, so I think it is ok.

2024-04-05 02:37 UTC, dhalbert approved these changes
Thanks for this!

2024-04-05 02:38 UTC, merged