Add board details and reporting to documentation utilities
adafruit/circuitpython pull request #9278
Opened 2024-05-26 15:44 UTC by timchinowsky

- Enhances `docs/shared_bindings_matrix.py` to optionally add more board details to the returned dict
- Adds `docs/board_summaries.py`, which creates `.csv` reports from that dict, enabling visualizations like [this](https://docs.google.com/spreadsheets/d/1fZiNTo8ByxCGwQAtYSaaCKXIRkBdApn435xuSkT-nzA/edit?usp=sharing)
- Useful for answering questions like "what boards use which ports and processors?",  "what boards have the most pins?", and "for what ports/processors is this module implemented?"
- Not sure if y'all want it in the repo, but I've found it helpful, thought I'd share

2024-05-29 21:07 UTC, tannewt requested changes
One request. Looks good otherwise. Neat spreadsheet!

2024-05-29 21:07 UTC, tannewt commented on docs/board_summaries.py
Since this isn't used in doc generation, mind moving it to tools?

2024-05-29 23:43 UTC, timchinowsky commented on docs/board_summaries.py
Wonder if you've got a prettier way of doing this relative import:

https://github.com/timchinowsky/circuitpython/blob/a3d7a2c4df70b69604fb4fb99d664155e3c70a2f/tools/board_summaries.py#L27C2-L27C3

2024-05-30 17:08 UTC, tannewt commented on docs/board_summaries.py
Nah, this we do this already: https://github.com/adafruit/circuitpython/blob/d8ca8421a09b1e5fee8fd29213c3ccc7914f5d8c/tools/build_release_files.py#L16

2024-05-30 17:08 UTC, tannewt approved these changes
Thank you!

2024-05-30 17:08 UTC, merged