Update readme to show the support status of the new esps
adafruit/circuitpython pull request #9309
Opened 2024-06-05 20:11 UTC by bill88t

H2 and C2 are alpha.
C2 outright "halts and catches fire" in some of my tests.
Memory/instruction errors, heap errors, all sorts of goodies.
I will be filing issues once I *hopefully* make repro code.

C3 and C6 are still fine being beta.
There is a lot of weirdness that isn't easily reproducible and can't be filed atm.
Also thread/zigbee is not implemented.

S3 is just as stable as S2 and ble is somewhat implemented now right?

OG ESP32 still not stable due to serial.

2024-06-06 15:04 UTC, bill88t commented
Average github actions moment.

2024-06-06 15:10 UTC, dhalbert commented
I am inclined just to remove the stability status from the README. I cover this in the release notes for each release. Having to PR changes to this is another thing to synchronize with the release notes.

2024-06-06 15:14 UTC, dhalbert commented
There could a cross-reference: "see the latest release notes" instead.

2024-06-08 19:46 UTC, bill88t commented
Updated to do what was requested. Please let me know if it's to your liking.

Actions still don't feel like working.

2024-06-08 21:47 UTC, dhalbert requested changes

2024-06-08 21:47 UTC, dhalbert commented on README.rst
> +The following ports are available: ``atmel-samd``, ``cxd56``, ``espressif``, ``litex``, ``mimxrt10xx``, ``nordic``, ``raspberrypi``, ``silabs`` (``efr32``), ``stm``, ``unix``.
```suggestion
The following ports are available: ``atmel-samd``, ``cxd56``, ``espressif``, ``litex``, ``mimxrt10xx``, ``nordic``, ``raspberrypi``, ``renode``, ``silabs`` (``efr32``), ``stm``, ``unix``.
```

2024-06-08 21:47 UTC, dhalbert commented on README.rst
> +However they are not all stable. For details, refer to the `latest release <https://github.com/adafruit/circuitpython/releases/latest>`__ notes.
```suggestion
However, not all ports are not fully functional. Some have limited limited functionality and known serious bugs.
For details, refer to the **Port status** section in the `latest release <https://github.com/adafruit/circuitpython/releases/latest>`__ notes.
```

2024-06-08 21:48 UTC, dhalbert approved these changes
I tweaked the language slightly and am merging. Thanks!

2024-06-17 15:21 UTC, dhalbert requested changes

2024-06-17 15:21 UTC, dhalbert commented on README.rst
> +However, not all ports are not fully functional. Some have limited limited functionality and known serious bugs.
```suggestion
However, not all ports are fully functional. Some have limited limited functionality and known serious bugs.
```

2024-06-17 15:22 UTC, dhalbert approved these changes

2024-06-17 15:34 UTC, merged