Update macos version in github actions
adafruit/circuitpython pull request #9329
Opened 2024-06-12 20:34 UTC by jepler

Move from 11 (deprecated) to 12 (the oldest non-deprecated)

Because the artifacts formerly had the macos version number in the
mpy-cross binary filename, we have to change the binary name anyway.
Rename it without the macos version (e.g., mpy-cross-macos-x64 instead of
mpy-cros-macos-11-x64)

https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/

Closes: #9328

2024-06-14 01:11 UTC, jepler commented
This also adds a new dependency on setuptools, needed for the silabs port when using python 3.12 and newer, which removed distutils

2024-06-14 18:17 UTC, bill88t requested changes
Removing the version name from the file itself but not the folder isn't ideal.
I know there is a `macos` folder already, but can't that be renamed to something else so that `macos` is used for this?

2024-06-14 18:30 UTC, jepler commented
@bill88t thanks, fixed

2024-06-14 18:35 UTC, bill88t approved these changes
Looks good!

2024-06-14 19:59 UTC, dhalbert approved these changes
Thank you for working this out. I won't merge in case we want to stage this with other PR's that will adjust the names and paths accordingly.

2024-06-15 14:56 UTC, jepler commented
I don't think there's anything we need to take care to do at the same moment. Until changed, for example, circuitpython_build_tools will always use mpy-cross from 9.0.0-alpha.2 (!) for creating its 9.x mpy files.

If we can drop 8.x from circuitpython_build_tools at the same time as we add 9.1 or 10, we can change it then to simply use the new path. If we need to keep 8.x support we'll need to add some version dependent checking for the mpy cross location. but I think this can all be handled in its own time and based on the issue I filed in circuitpython_build_tools.

2024-06-15 14:57 UTC, merged