Update pins.c for m5dial
adafruit/circuitpython pull request #9404
Opened 2024-07-04 09:06 UTC by mumin50

Hi All my first pull request ever :)
I just realised i miss SDA and SCL pins for M5Dial NFC reader, it is connected directly to board.I2C but in some usages having those pins will make things easier

2024-07-04 09:37 UTC, mumin50 commented
Tested on my side 
`Adafruit CircuitPython 9.1.0-beta.4-2-gc64bdf2c74 on 2024-07-04; M5Stack Dial with ESP32S3
>>> import board
>>> dir(board)
['__class__', '__name__', 'A1', 'A2', 'BOOT0', 'BUTTON', 'D0', 'D1', 'D13', 'D15', 'D2', 'DISPLAY', 'ENC_A', 'ENC_B', 'I2C', 'KNOB_BUTTON', 'MOSI', 'NEOPIXEL', 'PORTA_I2C', 'PORTB_IN', 'PORTB_OUT', 'POWER_HOLD', 'RFID_IRQ', 'RFID_SCL', 'RFID_SDA', 'SCK', 'SCL', 'SDA', 'SPEAKER', 'SPI', 'TFT_BACKLIGHT', 'TFT_CS', 'TFT_DC', 'TFT_RESET', 'TOUCH_IRQ', '__dict__', 'board_id']
>>>`

2024-07-04 13:10 UTC, dhalbert requested changes
I'm not sure of the naming here. `board.PORTA_I2C()` uses the GPIO13/15 for its SDA/SCL. But those pins are `board.SDA` and `board.SCL`. Normally `board.I2C` would use `board.SDA` and `board.SCL`. But here `board.I2C()` uses `board.RFID_SDA` and `board.RFID_SCL`.

From `mpconfigboard.h`:
```c
#define CIRCUITPY_BOARD_I2C_PIN     {{.scl = &pin_GPIO12, .sda = &pin_GPIO11}, \
                                     {.scl = &pin_GPIO15, .sda = &pin_GPIO13}}
```
Are `board.RFID_SDA` and `board.RFID_SCL` broken out for general use, or are they strictly internal for the RFID? If the latter, then I'd suggest `board.RFID_I2C()` for them, and `board.I2C()` for the Port A SDA and SCL instead.

2024-07-04 13:12 UTC, dhalbert commented
@CDarius You did the original naming. What do you think?

2024-07-05 06:21 UTC, CDarius commented
The `board.I2C()` (pins 11 and 12) is internal (not broken out) but it serves two peripherals: RFID and RTC.
I agree that having pin 13 `board.SDA` and  pin 15 `board.SCL` on `board.PORTA_I2C()` may be confusing.
I suggest the following changes:

- Rename `board.SDA` in `board.PORTA_SDA` (pin 13)
- Rename `board.SCL` in `board.PORTA_SCL` (pin 15)
- Add `board.SDA` on pin 11
- Add `board.SCL` on pin 12

2024-07-05 06:44 UTC, mumin50 commented
I just also realised it is used for other devices on I2C so probably naming is wrong. Sorry i was only using RFID for now so perchaps like CDarius mentioned would be better

2024-07-09 17:55 UTC, dhalbert commented
@CDarius' suggestion makes sense to me, as it is consistent with `m5stack_paper` and some other `m5stack` boards. There are also some examples of a different naming scheme with `SYS_i2C`, but there are more boards with the plain `I2C()` as the internal one, so we can stick with that.

2024-07-09 17:58 UTC, dhalbert commented
I made the changes. @mumin50 and @CDarius, could you double-check that this is OK?

2024-07-09 19:12 UTC, dhalbert approved these changes
I double-checked so I'll go ahead and merge.

2024-07-09 19:12 UTC, merged

2024-08-07 17:28 UTC, mumin50 commented
Works ok thank You