port for WeAct Studio H723VG-LCD dev board
adafruit/circuitpython pull request #9550
Opened 2024-08-22 19:03 UTC by bshewan

Port for this board: https://github.com/WeActStudio/WeActStudio.MiniSTM32H723
- includes:
  - support for the QSPI Flash as the main CIRCUITPY drive
  - support for OLED display
  - support for the SD card

2024-08-27 21:10 UTC, tannewt requested changes
Thanks for the changes! I'd love to support the 723. However, I'm concerned that some of these changes will break the existing H7 support.

2024-08-27 21:10 UTC, tannewt commented on ports/stm/boards/common_tcm.ld
> +    _ld_heap_end = ORIGIN(RAM) + LENGTH(RAM) - 1;
What is the last byte used for?

2024-08-27 21:10 UTC, tannewt commented on ports/stm/boards/weact-h723vg-lcd/mpconfigboard.mk
> +USB_PID = 0x5740
This is a generic STM VID/PID. If you don't work for WeAct you can request a USB PID from: https://pid.codes/ If you do work for WeAct, then you should sublicense a unique PID from STM or acquire your own VID from the USB folks.

2024-08-27 21:10 UTC, tannewt commented on ports/stm/hal_conf/stm32h7xx_hal_conf.h
> +#define HSE_VALUE    ((uint32_t)25000000) /*!< Value of the External oscillator in Hz : FPGA case fixed to 60MHZ */
Why change the default? Shouldn't the board define this?

2024-08-27 21:10 UTC, tannewt commented on ports/stm/peripherals/stm32h7/clocks.c
> +    RCC_OscInitStruct.PLL.PLLM = 2;
Does this break other H7 boards?

2024-08-27 21:10 UTC, tannewt commented on ports/stm/supervisor/internal_flash.c
> +    // EraseInitStruct.Banks = get_bank(_cache_flash_addr);
Why not set this?

2024-08-27 21:10 UTC, tannewt commented on ports/stm/supervisor/usb.c
> +    __HAL_RCC_USB_OTG_HS_CLK_ENABLE();
Do some H7 have two USB peripherals? The board should probably configure which to use.

2025-01-07 19:21 UTC, dhalbert commented
I'm closing this now due to lack of further work. We can always reopen it.

2025-01-07 19:21 UTC, closed without merging