add support for new custom board - CircuitArt ESP32S3 zero
adafruit/circuitpython pull request #9593
Opened 2024-09-04 12:27 UTC by CircuitART

This is a custom board that i developed it using the same footprint as pi zero.
the PID was obtained from Espressif https://github.com/espressif/usb-pids/pull/33
I have already build and tested circuitpython on it, and so far all is good

2024-09-04 16:48 UTC, tannewt requested changes
What happened to the Feather S3 that you requested the PID for? It is weird you are reusing it.

2024-09-04 16:48 UTC, tannewt commented on ports/espressif/boards/circuitart_zero_s3/mpconfigboard.mk
> +USB_MANUFACTURER = "CircuiArt"
```suggestion
USB_MANUFACTURER = "CircuitArt"
```

2024-09-04 16:55 UTC, CircuitART commented
my Feather S3 project was canceled and replaced with the zero version, I opened new pull request in espressif pid requesting changes on the pid name as well

2024-09-04 17:16 UTC, tannewt approved these changes
Ok, thanks!

2024-09-04 17:16 UTC, merged

2024-09-05 03:12 UTC, CircuitART commented
@tannewt just thought to let u know know that Espressif-pid has been changed successfully
https://github.com/espressif/usb-pids/pull/179

2024-09-05 17:11 UTC, tannewt commented
Thank you @CircuitART