rp2pio: Support PIOv1 features
adafruit/circuitpython pull request #9610
Opened 2024-09-10 19:11 UTC by jepler

This is needed to fully support the .mov_status and .fifo directives, as well as checking for PIO version compatibility between program & runtime hardware.

2024-09-13 15:12 UTC, jepler commented
Going to punt on extending consider_instruction for now.

2024-09-13 17:24 UTC, tannewt requested changes
Thanks for adding this support! Just a few minor things.

2024-09-13 17:24 UTC, tannewt commented on ports/raspberrypi/bindings/rp2pio/StateMachine.c
> +//|     """Accecss the state machine's rxfifo directly
```suggestion
//|     """Access the state machine's rxfifo directly
```

2024-09-13 17:24 UTC, tannewt commented on ports/raspberrypi/bindings/rp2pio/StateMachine.c
> +//|     the result of accessing it is undefined..
```suggestion
//|     the result of accessing it is undefined.
```

2024-09-13 17:24 UTC, tannewt commented on ports/raspberrypi/common-hal/rp2pio/StateMachine.c
> +        : 4;
Please add parens or switch to if statements. Nested ternary is very hard for me to read.

2024-09-13 17:24 UTC, tannewt commented on ports/raspberrypi/common-hal/rp2pio/StateMachine.h
> +    memorymap_addressrange_obj_t rxfifo_obj;
Want to wrap this in the version test to save object size on rp2040?

2024-09-16 18:47 UTC, tannewt approved these changes
Thank you! Looks good!

2024-09-16 18:48 UTC, merged