Fix json.dump/dumps() with IPv4Address
adafruit/circuitpython pull request #9769
Opened 2024-10-28 18:19 UTC by romkey

Change ipaddress_ipv4address_print() to quote the IPv4Address if kind is PRINT_JSON

Fixes [issue 9768](https://github.com/adafruit/circuitpython/issues/9768)

Without fix:
<img width="465" alt="Screenshot 2024-10-28 at 11 12 40 AM" src="https://github.com/user-attachments/assets/2f92e0c2-8d3a-42dc-8e4f-9e8bf68aae4b">
With fix:
<img width="504" alt="Screenshot 2024-10-28 at 11 19 32 AM" src="https://github.com/user-attachments/assets/2d32b6a0-5064-4cb4-848d-c2159ad20a37">

2024-11-02 17:14 UTC, dhalbert requested changes
See https://github.com/adafruit/circuitpython/issues/9768#issuecomment-2453051428. We want to be compatible with CPython, which will not produce valid JSON with an `ipaddress.IPv4Address` object either. But instead we should print the address as `IPv4Address(...)`, and similarly for IPv6Address.

2024-11-02 18:33 UTC, jepler commented
This issue has been reported upstream at Micropython with the response that "This was a design decision. It's undefined behaviour if you serialise something that can't be serialised" https://github.com/micropython/micropython/issues/1719

2024-11-02 18:35 UTC, jepler commented
And documented in Micropython. we may not be reproducing this portion of the documentation in the circuitpython online docs. https://docs.micropython.org/en/latest/genrst/modules.html#json-module-does-not-throw-exception-when-object-is-not-serialisable

2024-11-04 16:47 UTC, closed without merging

2024-11-04 17:15 UTC, dhalbert commented
This is subsumed by #9789.