Add BlockBiquad shelf & peaking, AudioFilter support
adafruit/circuitpython pull request #9804
Opened 2024-11-11 17:27 UTC by jepler

@relic-se @gamblor21 @todbot for interest.

A potential limitation is:
>  Using the same LFO as an input to multiple other LFOs or Notes is OK, but the result if an LFO is tied to multiple Synthtesizer[sic, someone should fix that doc typo] objects is undefined.

(besides which, LFOs can now be used with AudioFilters, BlockBiquads, and other types of objects; LFOs, Math blocks and BlockBiquads should in the medium term be moved out of synthio into their own modules and the documentation updated to reflect what they can be used with)

AudioFilter is more likely to be used with AudioMixer. But you can't have one LFO drive the filters of two different AudioFilter objects.

I honestly don't know what the fix for this is. The `lfo_tick` routine needs to run once every SYNTHIO_MAX_DUR samples, but other parts of the audio pipeline produce or consume in different chunks. Using AudioMixer to gather up multiple chunks of synthio data is a common trick, but you still want the LFOs to tick every 256 samples even if AudioMixer is gathering 1024 samples at a time (ssay) In fact, this is making me doubt that a BlockBiquad with varying inputs is even working right in Filter with a single Filter and no mixer since it is using buffer_size of 512 bytes which might or might not be 256 samples.

This needs more thought, so I'm entering this as a draft.

2024-12-05 17:25 UTC, relic-se commented
The updates look great to me so far, and I'm happy with the updates to `audiofilters.Filter`. Namely, the rewrite of `common_hal_audiofilters_filter_set_filter` and removal of `reset_filter_states`.

2024-12-05 17:42 UTC, jepler commented
@relic-se can you comment on this specifically?
> this is making me doubt that a BlockBiquad with varying inputs is even working right in Filter with a single Filter and no mixer since it is using buffer_size of 512 bytes which might or might not be 256 samples.

2024-12-05 18:01 UTC, relic-se commented
@jepler Since the `synthio.BlockInput` system relies on an actively running instance of `synthio.Synthesizer` to operate, it isn't currently possible to use `audiofilters.Filter` without also using `audiomixer.Mixer` with two voices, one reserved for `synthio.Synthesizer` (even if it isn't doing anything other thank BlockInput calculations).

Here's an example of this in action: https://gist.github.com/relic-se/77e48df1920b20d3e50762cbc06d1bb9#file-audioeffects_microphone-py-L111-L112.

If `synthio.BlockInput` is separated from `synthio.Synthesizer` in the future, I think that's something that we can dive deeper into. I suspect that a static counter of some sort on whatever updates `synthio.BlockInput` would be used to mitigate this problem.

2024-12-05 18:09 UTC, jepler commented
Just like using an LFO, math, or other object with a block input with two synthesizer objects is undefined, so is using an LFO with a synthesizer and an audiofilter...:
```
//|     Using the same LFO as an input to multiple other LFOs or Notes is OK, but            
//|     the result if an LFO is tied to multiple Synthtesizer objects is undefined.          
```
so sadly I have to say that the code linked above is relying on undefined behavior. I wish I had looked more closely at the use of block inputs in audiofilters because I would have asked that it be reworked to not rely on a side effect of a synthio.Synthesizer in this way.

2025-01-23 23:16 UTC, relic-se commented on shared-module/audiofilters/Filter.c
> +    shared_bindings_synthio_lfo_tick(self->sample_rate);
Following the merge of #9776 , `shared_bindings_synthio_lfo_tick` and all `synthio_block_slot_get` calls will need to be moved into the buffer loop at L258, a second `num_samples` argument will need to be provided, and the buffer loop will need to be limited to `SYNTHIO_MAX_DUR` samples per iteration. See Distortion.c for a good example of this which also ticks the blocks when no sample is provided.
https://github.com/adafruit/circuitpython/blob/10cd4f091c8a3d556df781deee0b1bd870c332ab/shared-module/audiofilters/Distortion.c#L217

2025-02-08 03:08 UTC, jepler commented
I've rebased this on main to resolve conflicts but I still need to mentally process & implement @relic-se's note about ticking in Filter.c. It's my hope that with some of my recent code saving PRs this might fit in flash now.

2025-02-08 15:39 UTC, jepler commented on shared-module/audiofilters/Filter.c
> +    shared_bindings_synthio_lfo_tick(self->sample_rate);
Please check back and see if what I did makes sense now.

2025-02-08 21:39 UTC, relic-se commented
@jepler I've checked over your get_buffer loop, and the ticking implementation looks right to me!

Would there be any significant flash savings from removing the original Biquads (as well as `synthio.low_pass_filter` etc) in a future CPy release?

2025-02-08 22:43 UTC, jepler commented
yeah, it would save code space for sure. I went ahead and added a deprecation notice to the docs. When we break ground on version 10 someone can remove the old versions.

note: actually, keeping the synthesizer methods but making them return BlockBiquads is going to cost hardly any code size but would be almost perfect for backwards compatibility. So maybe do that instead.

2025-02-13 18:34 UTC, tannewt requested changes
One small documentation thing. Good otherwise! Please file a 10.0.0 issue to remove the old way. 9.2.4+ can be the transition versions.

2025-02-13 18:34 UTC, tannewt commented on shared-bindings/synthio/BlockBiquad.c
> +//|     """A notch filter"""
Update these descriptions.

2025-02-14 01:26 UTC, jepler commented on shared-bindings/synthio/BlockBiquad.c
> +//|     """A notch filter"""
Done.

2025-02-14 05:13 UTC, tannewt approved these changes
Thank you!

2025-02-14 05:17 UTC, merged